import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { describe, expect, it } from 'vitest';
import { SchedulerDatabase, WorkflowTreeDatabase, type SchedulerBackend, type SchedulerSession } from '@mayura/storage-sql/host';
import type { WorkflowTreeManifest, WorkflowTreePolicyManifest } from '@mayura/storage-contracts';
import { workflowTreeState } from '@mayura/storage-contracts';

const connectionString=process.env['MAYURA_TEST_POSTGRES_URL'];
const suite=connectionString?describe:describe.skip;
const manifest:WorkflowTreeManifest={format:4,id:'root',version:'1',graph:[{kind:'child',id:'child',dependsOn:[],workflow:{id:'leaf',version:'1',graph:[{kind:'tool',id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none',capabilities:[],costMicros:2,approval:false,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}},policy:{permissions:['tool:fixture/tool'],maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000},resources:{work:[]},input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'child',path:[]}};
const policy:WorkflowTreePolicyManifest={scope:{principalId:'owner',projectId:'project'},permissions:['tool:fixture/tool'],policyVersion:'1',maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000};

function session(client:PoolClient):SchedulerSession{return{query:async<T>(sql:string,parameters:readonly unknown[]=[])=>{let ordinal=0;const result=await client.query(sql.replace(/\?/g,()=>`$${++ordinal}`),[...parameters]);return result.rows as T[];}};}

suite('workflow-tree PostgreSQL root enrollment',()=>{
  it('atomically creates and reopens the fixed profile-3 root',async()=>{
    const schema=`mayura_tree_${randomUUID().replaceAll('-','')}`;const pool=new Pool({connectionString:connectionString!,max:4});
    const transaction=async<T>(body:(tx:SchedulerSession)=>Promise<T>):Promise<T>=>{const client=await pool.connect();try{await client.query('BEGIN');const result=await body(session(client));await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}};
    const prefix=`"${schema}".`;const backend:SchedulerBackend={dialect:'postgres',prefix,transaction};
    try{
      await pool.query(`CREATE SCHEMA "${schema}"`);await pool.query(`CREATE TABLE ${prefix}mayura_aggregates (scope TEXT NOT NULL,id TEXT NOT NULL,idempotency_key TEXT NOT NULL,definition_hash TEXT NOT NULL,submission_digest TEXT NOT NULL,version BIGINT NOT NULL,event_sequence BIGINT NOT NULL,state TEXT NOT NULL,PRIMARY KEY(scope,id),UNIQUE(scope,idempotency_key))`);await pool.query(`CREATE TABLE ${prefix}mayura_events (scope TEXT NOT NULL,aggregate_id TEXT NOT NULL,sequence BIGINT NOT NULL,type TEXT NOT NULL,data TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(scope,aggregate_id,sequence),FOREIGN KEY(scope,aggregate_id) REFERENCES ${prefix}mayura_aggregates(scope,id))`);await pool.query(`CREATE TABLE ${prefix}mayura_workflow_owners (scope TEXT NOT NULL,aggregate_id TEXT NOT NULL,profile INTEGER NOT NULL,aggregate_version BIGINT NOT NULL,definition_hash TEXT NOT NULL,policy_hash TEXT NOT NULL,resource_hash TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(scope,aggregate_id),FOREIGN KEY(scope,aggregate_id) REFERENCES ${prefix}mayura_aggregates(scope,id))`);
      const trees=new WorkflowTreeDatabase(backend,new SchedulerDatabase(backend));await trees.initialize();const first=await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'});expect(first.created).toBe(true);
      const reopened=new WorkflowTreeDatabase(backend,new SchedulerDatabase(backend));await reopened.initialize();const command={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,parentId:first.snapshot.rootId,nodeId:'child',expectedVersion:1,input:null};
      const raced=await Promise.all([trees.admitChild(command),reopened.admitChild(command)]);expect(raced.filter(item=>item.created)).toHaveLength(1);expect(new Set(raced.map(item=>item.childId))).toHaveLength(1);const admitted=raced[0]!;
      const retry=await reopened.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'});expect(retry.created).toBe(false);expect(retry.snapshot.record.version).toBe(2);
      const childRetry=await reopened.admitChild({scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,parentId:first.snapshot.rootId,nodeId:'child',expectedVersion:1,input:null});expect(childRetry.created).toBe(false);expect(childRetry.childId).toBe(admitted.childId);
      const prepare={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,childId:admitted.childId,childPolicyHash:admitted.policyHash,nodeId:'work',expectedVersion:1,input:null};const prepared=await Promise.all([trees.prepareChildTool(prepare),reopened.prepareChildTool(prepare)]);expect(prepared.filter(item=>item.created)).toHaveLength(1);expect(new Set(prepared.map(item=>item.job.jobId))).toHaveLength(1);
      const claims=await Promise.all([trees.claimPreparedChildTool({...prepare,workerId:'worker-a',leaseMs:1_000}),reopened.claimPreparedChildTool({...prepare,workerId:'worker-b',leaseMs:1_000})]);expect(claims.filter(Boolean)).toHaveLength(1);const claimed=claims.find(Boolean);expect(claimed?.job).toMatchObject({state:'leased',fence:1});if(!claimed)throw new Error('fixture');
      const start={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,childId:admitted.childId,childPolicyHash:admitted.policyHash,nodeId:'work',expectedVersion:claimed.member.version,claim:claimed.claim,input:null};const starts=await Promise.all([trees.startClaimedChildTool(start),reopened.startClaimedChildTool(start)]);expect(starts.map(item=>item.status).sort()).toEqual(['already_started','started']);expect(starts[0]!.root.budget.accounts.find(account=>account.id===admitted.accountId)).toMatchObject({calls:1,heldCalls:0,reservedMicros:2});
      const receipt={callId:`${admitted.childId}/step:work`,toolId:'fixture/tool',execution:'succeeded' as const,disclosure:'withheld' as const};const evidence={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,childId:admitted.childId,childPolicyHash:admitted.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'evidence-1',receipt};const receipts=await Promise.all([trees.recordChildToolReceipt(evidence),reopened.recordChildToolReceipt(evidence)]);expect(receipts.every(item=>item.root.record.version===5)).toBe(true);expect(receipts[0]!.root.budget.accounts.find(account=>account.id===admitted.accountId)).toMatchObject({spentMicros:2,reservedMicros:0,calls:1});
      const completion={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,childId:admitted.childId,childPolicyHash:admitted.policyHash,nodeId:'work',claim:claimed.claim,commandId:'complete-1',evidenceId:'evidence-1',outcome:'succeeded' as const,output:{answer:42}};const completions=await Promise.all([trees.completeChildTool(completion),reopened.completeChildTool(completion)]);expect(completions.every(item=>item.member.version===6&&item.job.state==='succeeded')).toBe(true);expect(workflowTreeState(completions[0]!.member)).toMatchObject({steps:{work:{status:'succeeded',output:{answer:42}}}});
      const finalization={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,childId:admitted.childId,childPolicyHash:admitted.policyHash,expectedVersion:completions[0]!.member.version,output:{answer:42}};const finalized=await Promise.all([trees.finalizeChild(finalization),reopened.finalizeChild(finalization)]);expect(finalized.every(item=>item.member.version===7&&item.root.record.version===6)).toBe(true);expect(finalized[0]!.root.budget.accounts.find(account=>account.id===admitted.accountId)).toMatchObject({closed:true,spentMicros:2,reservedMicros:0});
      const join={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,nodeId:'child',expectedVersion:finalized[0]!.root.record.version};const joined=await Promise.all([trees.joinChild(join),reopened.joinChild(join)]);expect(joined.every(item=>item.record.version===7)).toBe(true);expect(workflowTreeState(joined[0]!.record)).toMatchObject({steps:{child:{status:'succeeded',output:{answer:42},child:{joinedVersion:7}}}});
      const rootCompletion={scope:first.snapshot.record.scope,rootId:first.snapshot.rootId,rootPolicyHash:first.snapshot.policyHash,expectedVersion:joined[0]!.record.version,output:{answer:42}};const finished=await Promise.all([trees.finalizeRoot(rootCompletion),reopened.finalizeRoot(rootCompletion)]);expect(finished.every(item=>item.record.version===8&&item.budget.version===7)).toBe(true);expect(workflowTreeState(finished[0]!.record)).toMatchObject({status:'succeeded',output:{answer:42}});expect(finished[0]!.budget.accounts.every(account=>account.closed)).toBe(true);
      const cancelRoot=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'cancel-root'})).snapshot;const cancelChild=await trees.admitChild({scope:cancelRoot.record.scope,rootId:cancelRoot.rootId,rootPolicyHash:cancelRoot.policyHash,parentId:cancelRoot.rootId,nodeId:'child',expectedVersion:1,input:null});const cancelPrepare={scope:cancelRoot.record.scope,rootId:cancelRoot.rootId,rootPolicyHash:cancelRoot.policyHash,childId:cancelChild.childId,childPolicyHash:cancelChild.policyHash,nodeId:'work',expectedVersion:1,input:null};await trees.prepareChildTool(cancelPrepare);const cancelClaim=await trees.claimPreparedChildTool({...cancelPrepare,workerId:'cancel-worker',leaseMs:1_000});if(!cancelClaim)throw new Error('fixture');await trees.startClaimedChildTool({...cancelPrepare,expectedVersion:cancelClaim.member.version,claim:cancelClaim.claim});const cancelCommand={scope:cancelRoot.record.scope,rootId:cancelRoot.rootId,rootPolicyHash:cancelRoot.policyHash,expectedVersion:4,commandId:'cancel-started'};const cancellations=await Promise.all([trees.cancelRoot(cancelCommand),reopened.cancelRoot(cancelCommand)]);expect(cancellations.every(item=>item.root.record.version===5&&workflowTreeState(item.root.record).status==='cancelled')).toBe(true);expect(cancellations.flatMap(item=>item.jobs)).toEqual([expect.objectContaining({state:'outcome_unknown'})]);expect(cancellations[0]!.root.budget.reservations).toEqual([expect.objectContaining({status:'unknown'})]);
      const late=await reopened.recordChildToolReceipt({scope:cancelRoot.record.scope,rootId:cancelRoot.rootId,rootPolicyHash:cancelRoot.policyHash,childId:cancelChild.childId,childPolicyHash:cancelChild.policyHash,nodeId:'work',fence:cancelClaim.claim.fence,evidenceId:'late-known',receipt:{callId:`${cancelChild.childId}/step:work`,toolId:'fixture/tool',execution:'failed',disclosure:'withheld'}});expect(late).toMatchObject({disposition:'late',root:{record:{version:6},budget:{version:8,reservations:[expect.objectContaining({status:'settled',actualMicros:2})]}}});expect(workflowTreeState(late.root.record)).toMatchObject({status:'cancelled',output:null});
      const counts=await pool.query(`SELECT (SELECT COUNT(*) FROM ${prefix}mayura_workflow_tree_budgets)::int AS budgets,(SELECT COUNT(*) FROM ${prefix}mayura_workflow_tree_members)::int AS members,(SELECT COUNT(*) FROM ${prefix}mayura_workflow_tree_jobs)::int AS jobs`);expect(counts.rows[0]).toEqual({budgets:2,members:4,jobs:2});
    }finally{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await pool.end();}
  });
});
