import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { describe,expect,it } from 'vitest';
import { createPostgresStore } from '@mayura/storage-postgres';
import type { WorkflowTreeManifest,WorkflowTreePolicyManifest } from '@mayura/storage-contracts';

const connectionString=process.env['MAYURA_TEST_POSTGRES_URL'];const suite=connectionString?describe:describe.skip;
const manifest:WorkflowTreeManifest={format:4,id:'plan-root',version:'1',graph:[{kind:'tool',id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none',capabilities:[],costMicros:1,approval:false,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}};
const policy:WorkflowTreePolicyManifest={scope:{principalId:'plan',projectId:'tree-discovery'},permissions:['tool:fixture/tool'],policyVersion:'selected',maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000};
suite('PostgreSQL workflow-tree discovery plan',()=>{it('uses the owner index over populated genuine format-4 history',async()=>{const schema=`mayura_tree_plan_${randomUUID().replaceAll('-','')}`;const store=createPostgresStore({connectionString:connectionString!,schema});try{await store.initialize();await store.workflowTrees.initialize();await store.workflowTreeDiscovery.initialize();for(let offset=0;offset<128;offset+=16)await Promise.all(Array.from({length:16},(_,step)=>{const index=offset+step;return store.workflowTrees.submit({manifest,policy:{...policy,policyVersion:`filler-${index}`},resources:{work:[]},input:null,idempotencyKey:`filler-${index}`});}));const selected=(await store.workflowTrees.submit({manifest,policy,resources:{work:[]},input:null,idempotencyKey:'selected'})).snapshot;const pool=new Pool({connectionString:connectionString!});try{await pool.query(`ANALYZE "${schema}".mayura_workflow_owners`);const plan=await pool.query(`EXPLAIN (FORMAT JSON) SELECT aggregate_id FROM "${schema}".mayura_workflow_owners WHERE scope = $1 AND policy_hash = $2 AND profile = 3 AND aggregate_id COLLATE "C" > $3 ORDER BY aggregate_id COLLATE "C" LIMIT $4`,[selected.record.scope,selected.policyHash,'',16]);const serialized=JSON.stringify(plan.rows);expect(serialized).toContain('mayura_workflow_owners_discovery');expect(serialized).toMatch(/Index (Only )?Scan/);expect(serialized).not.toContain('Seq Scan');}finally{await pool.end();}const page=await store.workflowTreeDiscovery.scan({scope:selected.record.scope,policyHash:selected.policyHash,cursor:null,limit:16});expect(page).toMatchObject({candidates:[{rootId:selected.rootId}],examined:1,nextCursor:null});}finally{await store.close();if(!/^mayura_tree_plan_[a-f0-9]{32}$/.test(schema))throw new Error('Unexpected fixture schema.');const pool=new Pool({connectionString:connectionString!});try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}},120_000);});
