import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { describe, expect, it } from 'vitest';
import { createPostgresStore } from '@mayura/storage-postgres';
import { workflowTreeState, type WorkflowTreeManifest, type WorkflowTreePolicyManifest } from '@mayura/storage-contracts';

const connectionString=process.env['MAYURA_TEST_POSTGRES_URL'];
const suite=connectionString?describe:describe.skip;
const leaf={id:'leaf',version:'1',graph:[{kind:'tool' as const,id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none' as const,capabilities:[],costMicros:2,approval:false,input:{kind:'input' as const,path:[]}}],result:{kind:'step' as const,stepId:'work',path:[]}};
const manifest:WorkflowTreeManifest={format:4,id:'root',version:'1',graph:[{kind:'child',id:'child',dependsOn:[],workflow:leaf,policy:{permissions:['tool:fixture/tool'],maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000},resources:{work:[]},input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'child',path:[]}};
const policy:WorkflowTreePolicyManifest={scope:{principalId:'owner',projectId:'project'},permissions:['tool:fixture/tool'],policyVersion:'1',maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000};

suite('PostgreSQL public workflow-tree capability',()=>{
  it('persists and reopens one complete format-4 tree through selected adapters',async()=>{
    const schema=`mayura_tree_api_${randomUUID().replaceAll('-','')}`;const open=()=>createPostgresStore({connectionString:connectionString!,schema});const stores=[open()];
    try{const store=stores[0]!;await store.initialize();await store.workflowTrees.initialize();const api=store.workflowTrees;const root=(await api.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'})).snapshot;const child=await api.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await store.workflowTreeDiscovery.initialize();expect(await store.workflowTreeDiscovery.scan({scope:root.record.scope,policyHash:root.policyHash,cursor:null,limit:32})).toMatchObject({candidates:[{rootId:root.rootId,status:'waiting'}],examined:2,nextCursor:null});const common={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work'};await api.prepareChildTool({...common,expectedVersion:1,input:null});const claimed=await api.claimPreparedChildTool({...common,workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await api.startClaimedChildTool({...common,expectedVersion:claimed.member.version,claim:claimed.claim,input:null});const receipt={callId:`${child.childId}/step:work`,toolId:'fixture/tool',execution:'succeeded' as const,disclosure:'withheld' as const};await api.recordChildToolReceipt({...common,fence:claimed.claim.fence,evidenceId:'known',receipt});const completed=await api.completeChildTool({...common,claim:claimed.claim,commandId:'complete',evidenceId:'known',outcome:'succeeded',output:{answer:42}});const finalized=await api.finalizeChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,expectedVersion:completed.member.version,output:{answer:42}});const joined=await api.joinChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'child',expectedVersion:finalized.root.record.version});const finished=await api.finalizeRoot({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:joined.record.version,output:{answer:42}});const reopened=open();stores.push(reopened);await reopened.initialize();await reopened.workflowTrees.initialize();await reopened.workflowTreeDiscovery.initialize();const restored=await reopened.workflowTrees.inspect({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash});expect(restored).toEqual(finished);expect(workflowTreeState(restored!.record)).toMatchObject({status:'succeeded',output:{answer:42}});expect(await reopened.workflowTreeDiscovery.scan({scope:root.record.scope,policyHash:root.policyHash,cursor:null,limit:32})).toMatchObject({candidates:[],examined:2,nextCursor:null});
    }finally{await Promise.all(stores.map(store=>store.close()));if(!/^mayura_tree_api_[a-f0-9]{32}$/.test(schema))throw new Error('Unexpected fixture schema.');const pool=new Pool({connectionString:connectionString!});try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}
  });
});
