import Database from 'better-sqlite3';
import { mkdtemp,realpath,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename,dirname,join,resolve } from 'node:path';
import { afterEach,beforeEach,describe,expect,it } from 'vitest';
import { createSqliteStore } from '@mayura/storage-sqlite';
import type { WorkflowTreeManifest,WorkflowTreePolicyManifest } from '@mayura/storage-contracts';

const manifest:WorkflowTreeManifest={format:4,id:'plan-root',version:'1',graph:[{kind:'tool',id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none',capabilities:[],costMicros:1,approval:false,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}};
const policy:WorkflowTreePolicyManifest={scope:{principalId:'plan',projectId:'tree-discovery'},permissions:['tool:fixture/tool'],policyVersion:'selected',maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000};
const prefix='mayura-tree-plan-';
describe('SQLite workflow-tree discovery plan',()=>{let directory:string;beforeEach(async()=>{directory=await mkdtemp(join(await realpath(tmpdir()),prefix));});afterEach(async()=>{const actual=await realpath(directory);const root=await realpath(tmpdir());if(dirname(actual)!==root||!basename(actual).startsWith(prefix)||resolve(actual)!==resolve(directory))throw new Error('Refusing cleanup outside fixture directory.');await rm(actual,{recursive:true,force:true});});it('uses the owner index over populated genuine format-4 history',async()=>{const filename=join(directory,'plan.sqlite');let store=createSqliteStore({filename});await store.initialize();await store.workflowTrees.initialize();await store.workflowTreeDiscovery.initialize();for(let index=0;index<128;index++)await store.workflowTrees.submit({manifest,policy:{...policy,policyVersion:`filler-${index}`},resources:{work:[]},input:null,idempotencyKey:`filler-${index}`});const selected=(await store.workflowTrees.submit({manifest,policy,resources:{work:[]},input:null,idempotencyKey:'selected'})).snapshot;await store.close();const database=new Database(filename);try{database.exec('ANALYZE mayura_workflow_owners');const plan=database.prepare('EXPLAIN QUERY PLAN SELECT aggregate_id FROM mayura_workflow_owners WHERE scope = ? AND policy_hash = ? AND profile = 3 AND aggregate_id COLLATE BINARY > ? ORDER BY aggregate_id COLLATE BINARY LIMIT ?').all(selected.record.scope,selected.policyHash,'',16);const serialized=JSON.stringify(plan);expect(serialized).toContain('mayura_workflow_owners_discovery');expect(serialized).toContain('SEARCH');expect(serialized).not.toContain('USE TEMP B-TREE');}finally{database.close();}store=createSqliteStore({filename});await store.initialize();await store.workflowTreeDiscovery.initialize();const page=await store.workflowTreeDiscovery.scan({scope:selected.record.scope,policyHash:selected.policyHash,cursor:null,limit:16});expect(page).toMatchObject({candidates:[{rootId:selected.rootId}],examined:1,nextCursor:null});await store.close();},120_000);});
