import { freezeJson,jsonValue,MayuraError,type ErrorCode } from '@mayura/core';
import type { WorkflowFleetHoldReader } from './fleet-control.js';
import { StorageError,type WorkflowTreeDiscoveryAggregateStore,type WorkflowTreeDiscoveryCursor } from '@mayura/storage-contracts';
import { assertWorkflowTree,treeManifest,type AnyWorkflowTree } from './children-definition.js';
import { createWorkflowTreeDiscovery } from './children-discovery.js';
import { createWorkflowTreeRuntime,type WorkflowTreeRuntimeOptions,type WorkflowTreeSnapshot } from './children-runtime.js';
import { digest } from './definition.js';
import type { WorkflowDrainOptions, WorkflowDrainReport } from './drain.js';

export interface WorkflowTreeCoordinatorOptions extends Omit<WorkflowTreeRuntimeOptions,'store'|'verifyHuman'|'maxConcurrentRuns'>{readonly store:WorkflowTreeDiscoveryAggregateStore;readonly definitions:readonly AnyWorkflowTree[];readonly maxPendingStorageOperations?:number;
  /** Durable fleet hold consulted before each page; while held nothing is discovered or driven. */
  readonly hold?:WorkflowFleetHoldReader;}
export type WorkflowTreeCandidateOutcome=
  |{readonly kind:'observed';readonly rootId:string;readonly definitionHash:string;readonly version:number;readonly status:WorkflowTreeSnapshot['status']}
  |{readonly kind:'skipped';readonly rootId:string;readonly definitionHash:string;readonly reason:'unregistered_definition'|'paused'}
  |{readonly kind:'failed';readonly rootId:string;readonly definitionHash:string;readonly code:ErrorCode}
  |{readonly kind:'not_attempted';readonly rootId:string;readonly definitionHash:string};
export type WorkflowTreePageReport=
  |{readonly status:'completed';readonly examined:number;readonly nextCursor:WorkflowTreeDiscoveryCursor|null;readonly outcomes:readonly WorkflowTreeCandidateOutcome[]}
  |{readonly status:'interrupted';readonly examined:number;readonly retryCursor:WorkflowTreeDiscoveryCursor|null;readonly code:ErrorCode;readonly outcomes:readonly WorkflowTreeCandidateOutcome[]};
export interface WorkflowTreeCoordinator{runPage(command?:{readonly cursor?:WorkflowTreeDiscoveryCursor|null;readonly limit?:number}):Promise<WorkflowTreePageReport>;close():Promise<void>;
  /** Admit no new wave, let admitted effects settle within the deadline, then close. */
  drain(options?:WorkflowDrainOptions):Promise<WorkflowDrainReport>;}

const methods=['initialize','submit','inspect','requestRootApproval','approveRootTool','prepareRootTool','claimPreparedRootTool','renewClaimedRootTool','startClaimedRootTool','recordRootToolReceipt','completeRootTool','inspectChild','admitChild','requestChildApproval','approveChildTool','prepareChildTool','claimPreparedChildTool','renewClaimedChildTool','startClaimedChildTool','recordChildToolReceipt','completeChildTool','finalizeChild','joinChild','finalizeRoot','cancelChild','cancelRoot','recoverExpired'] as const;
const codes=new Set<ErrorCode>(['INVALID_CONFIG','INVALID_INPUT','INVALID_OUTPUT','INVALID_JSON','PERMISSION_DENIED','BUDGET_EXCEEDED','LIMIT_EXCEEDED','CANCELLED','TIMEOUT','TOOL_FAILED','MODEL_FAILED','GUARD_BLOCKED','GUARD_UNAVAILABLE','OUTCOME_UNKNOWN','UNSUPPORTED_PROFILE','NOT_FOUND','CONFLICT','STORAGE_UNAVAILABLE']);
const statuses=new Set<WorkflowTreeSnapshot['status']>(['running','waiting','paused','succeeded','failed','blocked','cancelled','outcome_unknown']);
const invalid=()=>new MayuraError('INVALID_CONFIG','Workflow-tree coordination requires a bounded genuine catalog and explicit worker policy.');
function fields(value:unknown,allowed:readonly string[],required:readonly string[]=[]):PropertyDescriptorMap{if(!value||typeof value!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw invalid();const result=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(result).some(key=>typeof key!=='string'||!allowed.includes(key))||Object.values(result).some(field=>!field.enumerable||!('value'in field))||required.some(key=>!Object.hasOwn(result,key)))throw invalid();return result;}
function member(value:object,name:string):unknown{let current:object|null=value;for(let depth=0;current&&depth<16;depth++,current=Object.getPrototypeOf(current) as object|null){const descriptor=Object.getOwnPropertyDescriptor(current,name);if(descriptor){if(!('value'in descriptor))throw invalid();return descriptor.value;}}throw invalid();}
function captured(source:unknown,names:readonly string[]){if(!source||typeof source!=='object')throw invalid();return Object.freeze(Object.fromEntries(names.map(name=>{const method=member(source,name);if(typeof method!=='function')throw invalid();return[name,(...args:unknown[])=>Reflect.apply(method,source,args)];})));}
function captureStore(value:unknown):WorkflowTreeDiscoveryAggregateStore{try{if(!value||typeof value!=='object')throw invalid();return Object.freeze({...captured(value,['events']),workflowTrees:captured(member(value,'workflowTrees'),methods),workflowTreeDiscovery:captured(member(value,'workflowTreeDiscovery'),['initialize','scan'])}) as unknown as WorkflowTreeDiscoveryAggregateStore;}catch{throw new MayuraError('UNSUPPORTED_PROFILE','The adapter must provide workflow-tree execution and discovery.');}}
function catalog(value:unknown):readonly AnyWorkflowTree[]{if(!Array.isArray(value)||value.length<1||value.length>32)throw invalid();const descriptors=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(descriptors).length!==value.length+1||Object.getOwnPropertySymbols(value).length)throw invalid();const seen=new Set<string>();let bytes=0;return Object.freeze(Array.from({length:value.length},(_,index)=>{const item=descriptors[String(index)];if(!item||!item.enumerable||!('value'in item))throw invalid();const definition=item.value as AnyWorkflowTree;assertWorkflowTree(definition);const manifest=treeManifest(definition);if(digest('mayura:workflow-tree:v1',manifest)!==definition.digest||seen.has(definition.digest))throw invalid();seen.add(definition.digest);bytes+=new TextEncoder().encode(JSON.stringify(manifest)).length;if(bytes>4_194_304)throw invalid();return definition;}));}
function safeCode(error:unknown):ErrorCode{try{if(error instanceof MayuraError||error instanceof StorageError){const field=Object.getOwnPropertyDescriptor(error,'code');const code:unknown=field&&'value'in field?field.value:undefined;if(code==='QUEUE_FULL')return'LIMIT_EXCEEDED';if(typeof code==='string'&&codes.has(code as ErrorCode))return code as ErrorCode;}}catch{/* Safe diagnostic boundary. */}return'STORAGE_UNAVAILABLE';}
function report(value:WorkflowTreePageReport):WorkflowTreePageReport{return freezeJson(jsonValue(value,{maxBytes:65_536,maxNodes:4_096,maxDepth:12})) as unknown as WorkflowTreePageReport;}

/** Finite fleet page over explicitly registered genuine format-4 definitions. */
export function createWorkflowTreeCoordinator(options:WorkflowTreeCoordinatorOptions):WorkflowTreeCoordinator{
  let descriptors:PropertyDescriptorMap;let definitions:readonly AnyWorkflowTree[];
  try{descriptors=fields(options,['store','definitions','scope','permissions','policyVersion','maxCostMicros','maxCalls','workerId','leaseMs','maxConcurrentJobs','maxOutputBytes','approvalTtlMs','storageTimeoutMs','maxPendingStorageOperations','hold'],['store','definitions','scope','permissions','policyVersion','maxCostMicros','maxCalls','workerId']);definitions=catalog(descriptors['definitions']!.value);}catch{throw invalid();}
  const store=captureStore(descriptors['store']!.value);const shared={store,scope:descriptors['scope']!.value as WorkflowTreeRuntimeOptions['scope'],permissions:descriptors['permissions']!.value as WorkflowTreeRuntimeOptions['permissions'],policyVersion:descriptors['policyVersion']!.value as string,maxCostMicros:descriptors['maxCostMicros']!.value as number,maxCalls:descriptors['maxCalls']!.value as number,workerId:descriptors['workerId']!.value as string,...(descriptors['leaseMs']?{leaseMs:descriptors['leaseMs'].value as number}:{}),...(descriptors['maxConcurrentJobs']?{maxConcurrentJobs:descriptors['maxConcurrentJobs'].value as number}:{}),...(descriptors['maxOutputBytes']?{maxOutputBytes:descriptors['maxOutputBytes'].value as number}:{}),...(descriptors['approvalTtlMs']?{approvalTtlMs:descriptors['approvalTtlMs'].value as number}:{}),...(descriptors['storageTimeoutMs']?{storageTimeoutMs:descriptors['storageTimeoutMs'].value as number}:{})};
  // The existing constructors perform the canonical policy and finite limit validation.
  const hold=descriptors['hold']?.value as WorkflowFleetHoldReader|undefined;if(hold!==undefined&&(hold===null||typeof hold!=='object'||typeof hold.isHeld!=='function'))throw invalid();
  const runtime=createWorkflowTreeRuntime({...shared,maxConcurrentRuns:1});const discovery=createWorkflowTreeDiscovery({store,scope:shared.scope,permissions:shared.permissions,policyVersion:shared.policyVersion,maxCostMicros:shared.maxCostMicros,maxCalls:shared.maxCalls,...(shared.maxOutputBytes===undefined?{}:{maxOutputBytes:shared.maxOutputBytes}),...(shared.approvalTtlMs===undefined?{}:{approvalTtlMs:shared.approvalTtlMs}),...(shared.storageTimeoutMs===undefined?{}:{storageTimeoutMs:shared.storageTimeoutMs}),...(descriptors['maxPendingStorageOperations']?{maxPendingStorageOperations:descriptors['maxPendingStorageOperations'].value as number}:{})});const registered=new Map(definitions.map(definition=>[definition.digest,definition]));let closed=false;let active=false;let closing:Promise<void>|undefined;
  return Object.freeze({async runPage(command={}){if(closed)throw new MayuraError('CANCELLED','Workflow-tree coordinator is closed.');if(active)throw new MayuraError('LIMIT_EXCEEDED','The coordinator already has one active page.');active=true;try{let admitted:{readonly cursor?:WorkflowTreeDiscoveryCursor|null;readonly limit?:number};try{admitted=freezeJson(jsonValue(command,{maxBytes:1_024})) as typeof admitted;}catch{throw new MayuraError('INVALID_INPUT','Workflow-tree coordination requires exact bounded page fields.');}
      // Fail closed: an unconfirmed hold state drives nothing.
      if(hold){let held:boolean;try{held=await hold.isHeld()===true;}catch{throw new MayuraError('STORAGE_UNAVAILABLE','Workflow-tree coordination could not confirm the fleet hold.');}if(held)return report({status:'interrupted',examined:0,retryCursor:admitted.cursor??null,code:'CANCELLED',outcomes:[]});}
      let page;try{page=await discovery.scan(admitted);}catch(error){throw closed?new MayuraError('CANCELLED','Workflow-tree coordinator is closed.'):new MayuraError(safeCode(error),'Workflow-tree coordination could not discover a valid page.');}const outcomes:WorkflowTreeCandidateOutcome[]=[];let stopped:ErrorCode|undefined;for(const candidate of page.candidates){if(closed||stopped){stopped??='CANCELLED';outcomes.push({kind:'not_attempted',rootId:candidate.rootId,definitionHash:candidate.definitionHash});continue;}if(candidate.status==='paused'){outcomes.push({kind:'skipped',rootId:candidate.rootId,definitionHash:candidate.definitionHash,reason:'paused'});continue;}const definition=registered.get(candidate.definitionHash);if(!definition){outcomes.push({kind:'skipped',rootId:candidate.rootId,definitionHash:candidate.definitionHash,reason:'unregistered_definition'});continue;}try{const result=await runtime.runUntilSettled(definition,candidate.rootId);if(result.id!==candidate.rootId||result.version<candidate.version||!statuses.has(result.status))throw new MayuraError('STORAGE_UNAVAILABLE','Continuation returned inconsistent identity metadata.');outcomes.push({kind:'observed',rootId:candidate.rootId,definitionHash:candidate.definitionHash,version:result.version,status:result.status});}catch(error){stopped=closed?'CANCELLED':safeCode(error);outcomes.push({kind:'failed',rootId:candidate.rootId,definitionHash:candidate.definitionHash,code:stopped});}}if(closed)stopped='CANCELLED';return stopped?report({status:'interrupted',examined:page.examined,retryCursor:admitted.cursor??null,code:stopped,outcomes}):report({status:'completed',examined:page.examined,nextCursor:page.nextCursor,outcomes});}finally{active=false;}},close(){if(!closing){closed=true;closing=Promise.allSettled([discovery.close(),runtime.close()]).then(()=>{});}return closing;},
    async drain(options){const report=await runtime.drain(options);closed=true;closing??=Promise.allSettled([discovery.close()]).then(()=>{});await closing;return report;}} satisfies WorkflowTreeCoordinator);
}
