import { Budget, MayuraError, assertPositiveInteger, freezeJson, jsonValue, validate, type ExecutionReceipt, type InferInput, type JsonValue, type Permissions, type Schema, type Scope } from '@mayura/core';
import { invokeTool } from '@mayura/tools';
import {
  StorageError, workflowTreePolicy, workflowTreeState,
  type Claim, type StoredRecord, type WorkflowTreeAggregateStore, type WorkflowTreeRootSnapshot as StoredTreeSnapshot, type WorkflowTreeStore,
} from '@mayura/storage-contracts';
import { assertWorkflow, digest, resolveBinding, type WorkflowNode } from './definition.js';
import { assertWorkflowTree, treeManifest, type AnyWorkflowTree, type WorkflowTreeDefinition } from './children-definition.js';
import type { VerifiedHuman } from './runtime.js';

export interface WorkflowTreeRuntimeOptions {
  readonly store:WorkflowTreeAggregateStore;readonly scope:Scope;readonly permissions:Permissions;readonly policyVersion:string;
  readonly maxCostMicros:number;readonly maxCalls:number;readonly workerId:string;readonly leaseMs?:number;
  readonly maxOutputBytes?:number;readonly approvalTtlMs?:number;readonly storageTimeoutMs?:number;
  readonly verifyHuman?:(credential:unknown)=>Promise<VerifiedHuman>;
}
export interface WorkflowTreeSnapshot {
  readonly id:string;readonly version:number;readonly status:ReturnType<typeof workflowTreeState>['status'];
  readonly steps:ReturnType<typeof workflowTreeState>['steps'];readonly output:JsonValue;
  readonly budget:StoredTreeSnapshot['budget'];
}
export interface WorkflowTreeChildSnapshot {readonly id:string;readonly version:number;readonly status:ReturnType<typeof workflowTreeState>['status'];readonly steps:ReturnType<typeof workflowTreeState>['steps'];readonly output:JsonValue;}
export interface WorkflowTreeRuntime {
  readonly profile:'scheduled-v3';
  submit<I extends Schema,O extends Schema>(definition:WorkflowTreeDefinition<I,O>,command:{readonly input:InferInput<I>;readonly idempotencyKey:string}):Promise<WorkflowTreeSnapshot>;
  inspect(id:string):Promise<WorkflowTreeSnapshot>;
  inspectChild(id:string,childId:string):Promise<WorkflowTreeChildSnapshot>;
  runUntilSettled(definition:AnyWorkflowTree,id:string):Promise<WorkflowTreeSnapshot>;
  approve(command:{readonly id:string;readonly childId?:string;readonly nodeId:string;readonly digest:string;readonly credential:unknown}):Promise<WorkflowTreeSnapshot>;
  cancel(id:string):Promise<WorkflowTreeSnapshot>;
  recoverExpired(id:string):Promise<WorkflowTreeSnapshot>;
  events(id:string,after?:number):ReturnType<WorkflowTreeAggregateStore['events']>;
  close():Promise<void>;
}

const terminal=new Set(['succeeded','failed','blocked','cancelled','outcome_unknown']);
const methods=(['initialize','submit','inspect','requestRootApproval','approveRootTool','prepareRootTool','claimPreparedRootTool','renewClaimedRootTool','startClaimedRootTool','recordRootToolReceipt','completeRootTool','inspectChild','admitChild','requestChildApproval','approveChildTool','prepareChildTool','claimPreparedChildTool','renewClaimedChildTool','startClaimedChildTool','recordChildToolReceipt','completeChildTool','finalizeChild','joinChild','finalizeRoot','cancelChild','cancelRoot','recoverExpired'] as const) satisfies readonly (keyof WorkflowTreeStore)[];

async function bounded<T>(operation:()=>Promise<T>,timeoutMs:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([Promise.resolve().then(operation),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new MayuraError('TIMEOUT','Workflow-tree validation or storage operation timed out.')),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}
function safe(value:unknown,maxBytes:number,label:string):JsonValue{try{return jsonValue(value,{maxBytes});}catch{throw new MayuraError('INVALID_INPUT',`Workflow-tree ${label} exceeds its bounded JSON contract.`);}}
function outputs(record:StoredRecord):Record<string,JsonValue>{const state=workflowTreeState(record);return Object.fromEntries(Object.entries(state.steps).filter(([,step])=>step.status==='succeeded').map(([id,step])=>[id,step.output]));}
function publicSnapshot(value:StoredTreeSnapshot):WorkflowTreeSnapshot{const state=workflowTreeState(value.record);return freezeJson(jsonValue({id:value.rootId,version:value.record.version,status:state.status,steps:state.steps,output:state.output,budget:value.budget})) as unknown as WorkflowTreeSnapshot;}
function publicChild(record:StoredRecord):WorkflowTreeChildSnapshot{const state=workflowTreeState(record);return freezeJson(jsonValue({id:record.id,version:record.version,status:state.status,steps:state.steps,output:state.output})) as unknown as WorkflowTreeChildSnapshot;}
function storageFailure(error:unknown):never{if(error instanceof StorageError&&['CONFLICT','NOT_FOUND','STALE_CLAIM','LIMIT_EXCEEDED'].includes(error.code))throw error;throw new MayuraError('STORAGE_UNAVAILABLE','Workflow-tree storage is unavailable; reconcile uncertain actions before retrying.');}

/** Finite format-4 driver for root-local tools and one-level required children. */
export function createWorkflowTreeRuntime(options:WorkflowTreeRuntimeOptions):WorkflowTreeRuntime{
  let api:WorkflowTreeStore;try{if(!options.store?.workflowTrees||methods.some(method=>typeof options.store.workflowTrees[method]!=='function'))throw new Error();api=Object.freeze(Object.fromEntries(methods.map(method=>[method,options.store.workflowTrees[method].bind(options.store.workflowTrees)]))) as unknown as WorkflowTreeStore;}catch{throw new MayuraError('UNSUPPORTED_PROFILE','This adapter does not provide the optional workflow-tree capability.');}
  const authority=workflowTreePolicy({scope:options.scope,permissions:options.permissions?.allow,policyVersion:options.policyVersion,maxCostMicros:options.maxCostMicros,maxCalls:options.maxCalls,maxOutputBytes:options.maxOutputBytes??65_536,approvalTtlMs:options.approvalTtlMs??3_600_000});
  if(typeof options.workerId!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$/.test(options.workerId))throw new MayuraError('INVALID_CONFIG','A bounded workflow-tree worker identity is required.');const leaseMs=options.leaseMs??3_000;const timeoutMs=options.storageTimeoutMs??10_000;assertPositiveInteger(leaseMs,'leaseMs');assertPositiveInteger(timeoutMs,'storageTimeoutMs');if(leaseMs<1_000||leaseMs>300_000)throw new MayuraError('INVALID_CONFIG','Workflow-tree lease must be between one second and five minutes.');
  const scopeKey=digest('mayura:scope:v1',authority.scope);const policyHash=digest('mayura:workflow-tree-policy:v1',authority);let initialized:Promise<void>|undefined;let closed=false;const active=new Map<string,AbortController>();const runs=new Map<string,{definition:AnyWorkflowTree;operation:Promise<WorkflowTreeSnapshot>}>();
  const open=():void=>{if(closed)throw new MayuraError('CANCELLED','Workflow-tree runtime is closed.');};const initialize=()=>initialized??=(async()=>{try{await bounded(()=>api.initialize(),timeoutMs);}catch(error){storageFailure(error);}})();const access=(id:string)=>{if(typeof id!=='string'||!/^[a-f0-9]{64}$/.test(id))throw new MayuraError('INVALID_INPUT','Workflow-tree run ID must be an exact hash.');return{scope:scopeKey,rootId:id,rootPolicyHash:policyHash};};
  const call=async<T>(operation:()=>Promise<T>):Promise<T>=>{try{return await bounded(operation,timeoutMs);}catch(error){return storageFailure(error);}};
  const inspectStored=async(id:string):Promise<StoredTreeSnapshot>=>{open();await initialize();const value=await call(()=>api.inspect(access(id)));if(!value)throw new MayuraError('NOT_FOUND','Workflow tree was not found in this scope.');if(value.rootId!==id||value.record.scope!==scopeKey||value.policyHash!==policyHash)throw new MayuraError('CONFLICT','Stored workflow-tree identity does not match this runtime.');workflowTreeState(value.record);return value;};
  const supported=(definition:AnyWorkflowTree):void=>{assertWorkflowTree(definition);for(const child of definition.nodes.filter(node=>node.kind==='child'))assertWorkflow(child.workflow);};
  const matchRoot=(definition:AnyWorkflowTree,root:StoredTreeSnapshot):void=>{if(root.manifestHash!==definition.digest||workflowTreeState(root.record).definition!==definition.digest)throw new MayuraError('CONFLICT','Stored workflow tree uses a different genuine definition.');};
  const receiptId=(jobId:string,fence:number,receipt:ExecutionReceipt)=>digest('mayura:workflow-tree-receipt:v1',{jobId,fence,receipt});

  async function executeRootTool(rootId:string,node:Extract<WorkflowNode,{kind:'tool'}>,record:StoredRecord,raw:JsonValue):Promise<boolean>{
    const base={...access(rootId),nodeId:node.id};try{await call(()=>api.prepareRootTool({...base,expectedVersion:record.version,input:raw}));}catch(error){if(error instanceof StorageError&&error.code==='CONFLICT')return false;throw error;}const claimed=await call(()=>api.claimPreparedRootTool({...base,workerId:options.workerId,leaseMs}));if(!claimed)return false;let token:Claim=claimed.claim;let renewal:ReturnType<typeof setTimeout>|undefined;let renewing:Promise<void>|undefined;let finished=false;const controller=new AbortController();active.set(claimed.job.jobId,controller);
    const schedule=()=>{if(finished||controller.signal.aborted)return;renewal=setTimeout(()=>{renewing=call(()=>api.renewClaimedRootTool({...base,claim:token,leaseMs})).then(result=>{token=result.claim;schedule();}).catch(()=>controller.abort());},Math.max(100,Math.floor(leaseMs/3)));};const stop=async()=>{finished=true;if(renewal)clearTimeout(renewal);await renewing;};let evidenceId:string|undefined;
    try{const result=await invokeTool(node.tool,raw,{runId:rootId,callId:`${rootId}/step:${node.id}`,scope:authority.scope,permissions:Object.freeze({allow:authority.permissions}),signal:controller.signal,budget:new Budget(node.tool.costMicros,1),maxOutputBytes:authority.maxOutputBytes,beforeDispatch:async input=>{const started=await call(()=>api.startClaimedRootTool({...base,expectedVersion:claimed.root.record.version,claim:token,input}));if(started.status!=='started')throw new MayuraError('CONFLICT','The root claim does not grant a fresh dispatch.');schedule();},onExecutionReceipt:async receipt=>{const withheld=Object.freeze({...receipt,disclosure:'withheld' as const});const currentEvidence=receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordRootToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));}});if(!result.receipt)return true;const withheld=Object.freeze({...result.receipt,disclosure:'withheld' as const});const currentEvidence=evidenceId??receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordRootToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));if(withheld.execution==='unknown')return true;await stop();const outcome=result.status==='succeeded'?'succeeded':withheld.execution==='failed'?'failed':'blocked';await call(()=>api.completeRootTool({...base,claim:token,commandId:crypto.randomUUID(),evidenceId:currentEvidence,outcome,output:result.status==='succeeded'?safe(result.output,authority.maxOutputBytes,'tool output'):null}));return true;}catch(error){if(error instanceof StorageError&&['STALE_CLAIM','CONFLICT'].includes(error.code))return true;throw error;}finally{await stop();active.delete(claimed.job.jobId);}
  }

  async function executeTool(rootId:string,childId:string,childPolicyHash:string,childPermissions:readonly string[],maxOutputBytes:number,node:Extract<WorkflowNode,{kind:'tool'}>,record:StoredRecord,raw:JsonValue):Promise<boolean>{
    const base={...access(rootId),childId,childPolicyHash,nodeId:node.id};try{await call(()=>api.prepareChildTool({...base,expectedVersion:record.version,input:raw}));}catch(error){if(error instanceof StorageError&&error.code==='CONFLICT')return false;throw error;}const claimed=await call(()=>api.claimPreparedChildTool({...base,workerId:options.workerId,leaseMs}));if(!claimed)return false;let token:Claim=claimed.claim;let renewal:ReturnType<typeof setTimeout>|undefined;let renewing:Promise<void>|undefined;let finished=false;const controller=new AbortController();active.set(claimed.job.jobId,controller);
    const schedule=()=>{if(finished||controller.signal.aborted)return;renewal=setTimeout(()=>{renewing=call(()=>api.renewClaimedChildTool({...base,claim:token,leaseMs})).then(result=>{token=result.claim;schedule();}).catch(()=>controller.abort());},Math.max(100,Math.floor(leaseMs/3)));};const stop=async()=>{finished=true;if(renewal)clearTimeout(renewal);await renewing;};let evidenceId:string|undefined;
    try{const result=await invokeTool(node.tool,raw,{runId:childId,callId:`${childId}/step:${node.id}`,scope:authority.scope,permissions:Object.freeze({allow:childPermissions}),signal:controller.signal,budget:new Budget(node.tool.costMicros,1),maxOutputBytes,beforeDispatch:async input=>{const started=await call(()=>api.startClaimedChildTool({...base,expectedVersion:claimed.member.version,claim:token,input}));if(started.status!=='started')throw new MayuraError('CONFLICT','The child claim does not grant a fresh dispatch.');schedule();},onExecutionReceipt:async receipt=>{const withheld=Object.freeze({...receipt,disclosure:'withheld' as const});const currentEvidence=receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordChildToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));}});if(!result.receipt)return true;const withheld=Object.freeze({...result.receipt,disclosure:'withheld' as const});const currentEvidence=evidenceId??receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordChildToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));if(withheld.execution==='unknown')return true;await stop();const outcome=result.status==='succeeded'?'succeeded':withheld.execution==='failed'?'failed':'blocked';await call(()=>api.completeChildTool({...base,claim:token,commandId:crypto.randomUUID(),evidenceId:currentEvidence,outcome,output:result.status==='succeeded'?safe(result.output,maxOutputBytes,'tool output'):null}));return true;}catch(error){if(error instanceof StorageError&&['STALE_CLAIM','CONFLICT'].includes(error.code))return true;throw error;}finally{await stop();active.delete(claimed.job.jobId);}
  }

  async function drive(definition:AnyWorkflowTree,id:string):Promise<WorkflowTreeSnapshot>{
    const rootNodes=definition.nodes.filter((node):node is Extract<WorkflowNode,{kind:'tool'}>=>node.kind==='tool');const childNodes=definition.nodes.filter(node=>node.kind==='child');for(let wave=0;wave<256;wave++){open();let root=await inspectStored(id);matchRoot(definition,root);let rootState=workflowTreeState(root.record);if(terminal.has(rootState.status)){if(rootState.status!=='succeeded'&&!root.budget.accounts.find(account=>account.id==='root')?.closed)root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}let progress=false;const recovery=await call(()=>api.recoverExpired({...access(id),limit:128}));if(recovery.jobs.length){root=recovery.root;rootState=workflowTreeState(root.record);progress=true;}
      for(const node of rootNodes){root=await inspectStored(id);rootState=workflowTreeState(root.record);const step=rootState.steps[node.id];if(!step||terminal.has(rootState.status)||!['pending','waiting','approved'].includes(step.status)||node.dependsOn?.some(dependency=>rootState.steps[dependency]?.status!=='succeeded'))continue;const required=[`tool:${node.tool.id}`,...node.tool.capabilities,...(node.tool.effects==='none'?[]:[`effect:${node.tool.effects}`])];if(required.some(grant=>!authority.permissions.includes(grant))){root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}let input:JsonValue;try{const raw=resolveBinding(node.input,rootState.input,outputs(root.record));input=safe(await validate(node.tool.input,raw,'input',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'tool input');}catch{root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}if(node.approval){const previousVersion=root.record.version;root=await call(()=>api.requestRootApproval({...access(id),nodeId:node.id,expectedVersion:previousVersion,input}));rootState=workflowTreeState(root.record);progress=root.record.version!==previousVersion||progress;if(rootState.steps[node.id]?.status!=='approved')break;}progress=await executeRootTool(id,node,root.record,input)||progress;break;}
      for(const childNode of childNodes){root=await inspectStored(id);rootState=workflowTreeState(root.record);const rootStep=rootState.steps[childNode.id];if(!rootStep||terminal.has(rootState.status))break;if(!rootStep.child&&childNode.dependsOn?.some(dependency=>rootState.steps[dependency]?.status!=='succeeded'))continue;let childRecord:StoredRecord;let childId:string;let childPolicyHash:string;if(!rootStep.child){const raw=resolveBinding(childNode.input,rootState.input,outputs(root.record));const input=safe(await validate(childNode.workflow.input,raw,'input',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'child input');const admitted=await call(()=>api.admitChild({...access(id),parentId:id,nodeId:childNode.id,expectedVersion:root.record.version,input}));root=admitted.root;childRecord=admitted.child;childId=admitted.childId;childPolicyHash=admitted.policyHash;progress||=admitted.created;}else{childId=rootStep.child.runId;childPolicyHash=rootStep.child.policyHash;childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;}
        let childState=workflowTreeState(childRecord);if(!terminal.has(childState.status)){for(const node of childNode.workflow.nodes){if(node.kind!=='tool')continue;childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;childState=workflowTreeState(childRecord);const step=childState.steps[node.id];if(!step||!['pending','waiting','approved'].includes(step.status)||node.dependsOn?.some(dependency=>childState.steps[dependency]?.status!=='succeeded'))continue;const required=[`tool:${node.tool.id}`,...node.tool.capabilities,...(node.tool.effects==='none'?[]:[`effect:${node.tool.effects}`])];if(required.some(grant=>!childNode.policy.permissions.includes(grant))){const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));childRecord=cancelled.member;progress=true;break;}let input:JsonValue;try{const raw=resolveBinding(node.input,childState.input,outputs(childRecord));input=safe(await validate(node.tool.input,raw,'input',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'tool input');}catch{const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));childRecord=cancelled.member;progress=true;break;}if(node.approval){const previousVersion=childRecord.version;const requested=await call(()=>api.requestChildApproval({...access(id),childId,childPolicyHash,nodeId:node.id,expectedVersion:previousVersion,input}));childRecord=requested.member;childState=workflowTreeState(childRecord);progress=childRecord.version!==previousVersion||progress;if(childState.steps[node.id]?.status!=='approved')break;}progress=await executeTool(id,childId,childPolicyHash,childNode.policy.permissions,childNode.policy.maxOutputBytes,node,childRecord,input)||progress;break;}
          childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;childState=workflowTreeState(childRecord);if(!terminal.has(childState.status)&&Object.values(childState.steps).every(step=>step.status==='succeeded')){let output:JsonValue|undefined;try{const raw=resolveBinding(childNode.workflow.result,childState.input,outputs(childRecord));output=safe(await validate(childNode.workflow.output,raw,'output',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'child output');}catch{const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));root=cancelled.root;childRecord=cancelled.member;progress=true;}if(output!==undefined){const finalized=await call(()=>api.finalizeChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,output}));root=finalized.root;childRecord=finalized.member;progress=true;}}
        }
        childState=workflowTreeState(childRecord);root=await inspectStored(id);rootState=workflowTreeState(root.record);if(terminal.has(childState.status)&&rootState.steps[childNode.id]?.child?.joinedVersion===null){root=await call(()=>api.joinChild({...access(id),nodeId:childNode.id,expectedVersion:root.record.version}));progress=true;if(workflowTreeState(root.record).status!=='succeeded'&&terminal.has(workflowTreeState(root.record).status)){root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}}
      }
      root=await inspectStored(id);rootState=workflowTreeState(root.record);if(Object.values(rootState.steps).every(step=>step.status==='succeeded')){let output:JsonValue;try{const raw=resolveBinding(definition.result,rootState.input,outputs(root.record));output=safe(await validate(definition.output,raw,'output',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'root output');}catch{root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}root=await call(()=>api.finalizeRoot({...access(id),expectedVersion:root.record.version,output}));return publicSnapshot(root);}
      if(!progress)return publicSnapshot(root);
    }throw new MayuraError('LIMIT_EXCEEDED','Workflow-tree continuation exceeded its finite progress bound.');
  }

  return Object.freeze<WorkflowTreeRuntime>({
    profile:'scheduled-v3',
    async submit(definition,command){open();supported(definition);if(typeof command.idempotencyKey!=='string'||!command.idempotencyKey.length||command.idempotencyKey.length>128)throw new MayuraError('INVALID_INPUT','A bounded stable submission key is required.');const raw=safe(command.input,authority.maxOutputBytes,'input');const input=safe(await validate(definition.input,raw,'input',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'input');await initialize();const result=await call(()=>api.submit({manifest:treeManifest(definition),policy:authority,resources:{},input,idempotencyKey:command.idempotencyKey}));matchRoot(definition,result.snapshot);return publicSnapshot(result.snapshot);},
    async inspect(id){return publicSnapshot(await inspectStored(id));},
    async inspectChild(id,childId){const root=await inspectStored(id);if(!/^[a-f0-9]{64}$/.test(childId))throw new MayuraError('INVALID_INPUT','Child run ID must be an exact hash.');const link=Object.values(workflowTreeState(root.record).steps).find(step=>step.child?.runId===childId)?.child;if(!link)throw new MayuraError('CONFLICT','Child is not owned by this workflow tree.');return publicChild((await call(()=>api.inspectChild({...access(id),childId,childPolicyHash:link.policyHash}))).member);},
    runUntilSettled(definition,id){open();supported(definition);access(id);const existing=runs.get(id);if(existing)return existing.definition===definition?existing.operation:Promise.reject(new MayuraError('CONFLICT','The active driver uses a different workflow-tree definition.'));const operation=drive(definition,id).finally(()=>runs.delete(id));runs.set(id,{definition,operation});return operation;},
    async approve(command){
      open();const root=await inspectStored(command.id);if((command.childId!==undefined&&!/^[a-f0-9]{64}$/.test(command.childId))||!/^[A-Za-z][A-Za-z0-9._-]{0,127}$/.test(command.nodeId)||!/^[a-f0-9]{64}$/.test(command.digest))throw new MayuraError('INVALID_INPUT','Approval requires exact member, node and review identities.');if(!options.verifyHuman)throw new MayuraError('PERMISSION_DENIED','A trusted human verifier is required.');let human:VerifiedHuman;try{human=await bounded(()=>options.verifyHuman!(command.credential),30_000);if(typeof human.id!=='string'||!human.id.length||/[\uD800-\uDFFF]/u.test(human.id)||new TextEncoder().encode(human.id).length>256||human.id.includes('\u0000')||human.projectId!==authority.scope.projectId||human.canApprove!==true)throw new Error();}catch{throw new MayuraError('PERMISSION_DENIED','Human verification did not authorize this approval.');}
      if(command.childId===undefined){await call(()=>api.approveRootTool({...access(command.id),nodeId:command.nodeId,expectedVersion:root.record.version,digest:command.digest,humanId:human.id}));return publicSnapshot(await inspectStored(command.id));}
      const childId=command.childId;const state=workflowTreeState(root.record);const link=Object.values(state.steps).find(step=>step.child?.runId===childId)?.child;if(!link)throw new MayuraError('CONFLICT','Child is not owned by this workflow tree.');const child=await call(()=>api.inspectChild({...access(command.id),childId,childPolicyHash:link.policyHash}));await call(()=>api.approveChildTool({...access(command.id),childId,childPolicyHash:link.policyHash,nodeId:command.nodeId,expectedVersion:child.member.version,digest:command.digest,humanId:human.id}));return publicSnapshot(await inspectStored(command.id));
    },
    async cancel(id){const root=await inspectStored(id);if(workflowTreeState(root.record).status==='succeeded')return publicSnapshot(root);return publicSnapshot((await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root);},
    async recoverExpired(id){await inspectStored(id);return publicSnapshot((await call(()=>api.recoverExpired({...access(id),limit:128}))).root);},
    async events(id,after=0){open();access(id);if(!Number.isSafeInteger(after)||after<0)throw new MayuraError('INVALID_INPUT','A non-negative event cursor is required.');await inspectStored(id);return call(()=>options.store.events(scopeKey,id,after));},
    async close(){if(closed)return;closed=true;for(const controller of active.values())controller.abort();await Promise.allSettled([...runs.values()].map(run=>run.operation));},
  });
}
