import { jsonValue,MayuraError,type ErrorCode,type JsonObject,type JsonValue } from '@mayura/core';
import {
  StorageError,workflowTreeDiscoveryCommand,workflowTreeDiscoveryPage,workflowTreePolicy,
  type WorkflowTreeDiscoveryAggregateStore,type WorkflowTreeDiscoveryCursor,type WorkflowTreeDiscoveryPage,
  type WorkflowTreeDiscoveryScan,type WorkflowTreeDiscoveryStore,
} from '@mayura/storage-contracts';
import { digest } from './definition.js';
import { scheduledCallback } from './scheduled-helpers.js';
import type { WorkflowTreeRuntimeOptions } from './children-runtime.js';

export type { WorkflowTreeDiscoveryCandidate,WorkflowTreeDiscoveryCursor,WorkflowTreeDiscoveryPage } from '@mayura/storage-contracts';
export interface WorkflowTreeDiscoveryOptions extends Pick<WorkflowTreeRuntimeOptions,'scope'|'permissions'|'policyVersion'|'maxCostMicros'|'maxCalls'|'maxOutputBytes'|'approvalTtlMs'>{readonly store:WorkflowTreeDiscoveryAggregateStore;readonly storageTimeoutMs?:number;readonly maxPendingStorageOperations?:number;}
export interface WorkflowTreeDiscovery{scan(command?:{readonly cursor?:WorkflowTreeDiscoveryCursor|null;readonly limit?:number}):Promise<WorkflowTreeDiscoveryPage>;
  /** The cursor that continues a scan after `rootId`, for callers that persist only the last root id. */
  cursorAfter(rootId:string):WorkflowTreeDiscoveryCursor;close():Promise<void>;}

const invalid=()=>new MayuraError('INVALID_INPUT','Workflow-tree discovery requires exact bounded fields and a cursor matching its configured scope and policy.');
function object(value:JsonValue):JsonObject{if(!value||typeof value!=='object'||Array.isArray(value))throw invalid();return value;}
function positive(value:unknown,fallback:number,maximum:number):number{const result=value===undefined?fallback:value;if(typeof result!=='number'||!Number.isSafeInteger(result)||result<1||result>maximum)throw invalid();return result;}
function member(value:object,name:string):unknown{let current:object|null=value;for(let depth=0;current&&depth<16;depth++,current=Object.getPrototypeOf(current) as object|null){const field=Object.getOwnPropertyDescriptor(current,name);if(field){if(!('value'in field))throw invalid();return field.value;}}throw invalid();}
function adapter(store:unknown):WorkflowTreeDiscoveryStore{try{if(!store||typeof store!=='object')throw invalid();const source=member(store,'workflowTreeDiscovery');if(!source||typeof source!=='object')throw invalid();const captured:Record<string,(...args:unknown[])=>unknown>={};for(const name of ['initialize','scan'] as const){const method=member(source,name);if(typeof method!=='function')throw invalid();captured[name]=(...args)=>Reflect.apply(method,source,args);}return Object.freeze(captured) as unknown as WorkflowTreeDiscoveryStore;}catch{throw new MayuraError('UNSUPPORTED_PROFILE','This adapter does not provide workflow-tree discovery.');}}
function storageFailure(error:unknown):MayuraError{let code:ErrorCode='STORAGE_UNAVAILABLE';try{const field=error instanceof StorageError?Object.getOwnPropertyDescriptor(error,'code'):undefined;const value:unknown=field&&'value'in field?field.value:undefined;if(value==='QUEUE_FULL')code='LIMIT_EXCEEDED';else if(['INVALID_INPUT','CONFLICT','NOT_FOUND','LIMIT_EXCEEDED'].includes(value as string))code=value as ErrorCode;}catch{/* Sanitized boundary. */}return new MayuraError(code,'Workflow-tree discovery could not confirm a valid observation page.');}

/** Finite metadata-only discovery; returned roots are hints, never dispatch grants. */
export function createWorkflowTreeDiscovery(options:WorkflowTreeDiscoveryOptions):WorkflowTreeDiscovery{
  let fields:PropertyDescriptorMap;let policy:ReturnType<typeof workflowTreePolicy>;let timeoutMs:number;let maxPending:number;
  try{if(!options||typeof options!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(options)))throw invalid();fields=Object.getOwnPropertyDescriptors(options);const allowed=['store','scope','permissions','policyVersion','maxCostMicros','maxCalls','maxOutputBytes','approvalTtlMs','storageTimeoutMs','maxPendingStorageOperations'];if(Reflect.ownKeys(fields).some(name=>typeof name!=='string'||!allowed.includes(name))||Object.values(fields).some(field=>!field.enumerable||!('value'in field)))throw invalid();const raw=object(jsonValue({scope:fields['scope']?.value,permissions:fields['permissions']?.value,policyVersion:fields['policyVersion']?.value,maxCostMicros:fields['maxCostMicros']?.value,maxCalls:fields['maxCalls']?.value,maxOutputBytes:fields['maxOutputBytes']?.value??65_536,approvalTtlMs:fields['approvalTtlMs']?.value??3_600_000}));const permissions=object(raw['permissions']!);if(Object.keys(permissions).length!==1||!Object.hasOwn(permissions,'allow'))throw invalid();policy=workflowTreePolicy({...raw,permissions:permissions['allow']});timeoutMs=positive(fields['storageTimeoutMs']?.value,10_000,30_000);maxPending=positive(fields['maxPendingStorageOperations']?.value,64,1_024);}catch{throw new MayuraError('INVALID_CONFIG','Workflow-tree discovery requires explicit tree policy and finite callback limits.');}
  const api=adapter(fields['store']?.value);const scope=digest('mayura:scope:v1',policy.scope);const policyHash=digest('mayura:workflow-tree-policy:v1',policy);const shutdown=new AbortController();let pending=0;let initialized:Promise<void>|undefined;const open=()=>{if(shutdown.signal.aborted)throw new MayuraError('CANCELLED','Workflow-tree discovery is closed.');};
  const call=async<T>(operation:()=>Promise<T>):Promise<T>=>{open();if(pending>=maxPending)throw new MayuraError('LIMIT_EXCEEDED','Workflow-tree discovery callback capacity is occupied.');pending++;const actual=Promise.resolve().then(()=>{open();return operation();}).finally(()=>{pending--;});void actual.catch(()=>{});try{return await scheduledCallback(()=>actual,timeoutMs,shutdown.signal);}catch(error){open();throw storageFailure(error);}};
  const initialize=async()=>{open();initialized??=(async()=>{if(await call(()=>api.initialize())!==undefined)throw new MayuraError('STORAGE_UNAVAILABLE','Invalid discovery initialization response.');open();})().catch(error=>{initialized=undefined;throw error;});await initialized;open();};
  return Object.freeze({cursorAfter(rootId:string):WorkflowTreeDiscoveryCursor{if(typeof rootId!=='string'||!/^[a-f0-9]{64}$/.test(rootId))throw invalid();return Object.freeze({format:1,scope,policyHash,afterId:rootId}) as WorkflowTreeDiscoveryCursor;},async scan(command={}){open();let admitted:WorkflowTreeDiscoveryScan;try{const raw=object(jsonValue(command,{maxBytes:1_024}));if(Object.keys(raw).some(name=>name!=='cursor'&&name!=='limit'))throw invalid();admitted=workflowTreeDiscoveryCommand('scan',{scope,policyHash,cursor:Object.hasOwn(raw,'cursor')?raw['cursor']:null,limit:Object.hasOwn(raw,'limit')?raw['limit']:16}) as unknown as WorkflowTreeDiscoveryScan;}catch{throw invalid();}await initialize();const raw=await call(()=>api.scan(admitted));open();try{return workflowTreeDiscoveryPage(raw,admitted);}catch{throw new MayuraError('STORAGE_UNAVAILABLE','Workflow-tree discovery returned an invalid page.');}},async close(){shutdown.abort();}} satisfies WorkflowTreeDiscovery);
}
