import { Budget, MayuraError, assertPositiveInteger, freezeJson, jsonValue, validate, type ExecutionReceipt, type InferInput, type JsonValue, type Permissions, type Schema, type Scope } from '@mayura/core';
import { invokeTool } from '@mayura/tools';
import { createWorkflowDrainGate, type WorkflowDrainOptions, type WorkflowDrainReport } from './drain.js';
import {
  StorageError, initialWorkflowTreeRootState, workflowTreePolicy, workflowTreeState,
  type Claim, type StoredRecord, type WorkflowTreeAggregateStore, type WorkflowTreeRootSnapshot as StoredTreeSnapshot, type WorkflowTreeStore,
} from '@mayura/storage-contracts';
import { assertWorkflow, digest, resolveBinding, type WorkflowNode } from './definition.js';
import { assertMigrationAllowed, assertWorkflowMigration, migrationCommand, nodeEvidence, nodeFingerprint, planWorkflowMigration,
  type MigrationBlocker, type MigrationCommand, type WorkflowMigration, type WorkflowMigrationResult } from './migration.js';
import { assertWorkflowTree, treeManifest, type AnyWorkflowTree, type WorkflowTreeDefinition } from './children-definition.js';
import type { VerifiedHuman } from './runtime.js';

export interface WorkflowTreeRuntimeOptions {
  readonly store:WorkflowTreeAggregateStore;readonly scope:Scope;readonly permissions:Permissions;readonly policyVersion:string;
  readonly maxCostMicros:number;readonly maxCalls:number;readonly workerId:string;readonly leaseMs?:number;
  readonly maxConcurrentJobs?:number;readonly maxConcurrentRuns?:number;
  readonly maxOutputBytes?:number;readonly approvalTtlMs?:number;readonly storageTimeoutMs?:number;
  readonly verifyHuman?:(credential:unknown)=>Promise<VerifiedHuman>;
}
export interface WorkflowTreeSnapshot {
  readonly id:string;readonly version:number;readonly status:ReturnType<typeof workflowTreeState>['status'];
  readonly steps:ReturnType<typeof workflowTreeState>['steps'];readonly output:JsonValue;
  readonly budget:StoredTreeSnapshot['budget'];
}
export interface WorkflowTreeChildSnapshot {readonly id:string;readonly version:number;readonly status:ReturnType<typeof workflowTreeState>['status'];readonly steps:ReturnType<typeof workflowTreeState>['steps'];readonly output:JsonValue;}
export interface WorkflowTreeRuntime {
  readonly profile:'scheduled-v3';
  submit<I extends Schema,O extends Schema>(definition:WorkflowTreeDefinition<I,O>,command:{readonly input:InferInput<I>;readonly idempotencyKey:string}):Promise<WorkflowTreeSnapshot>;
  inspect(id:string):Promise<WorkflowTreeSnapshot>;
  inspectChild(id:string,childId:string):Promise<WorkflowTreeChildSnapshot>;
  runUntilSettled(definition:AnyWorkflowTree,id:string):Promise<WorkflowTreeSnapshot>;
  approve(command:{readonly id:string;readonly childId?:string;readonly nodeId:string;readonly digest:string;readonly credential:unknown}):Promise<WorkflowTreeSnapshot>;
  cancel(id:string):Promise<WorkflowTreeSnapshot>;
  /** Persist a tree-wide quiescent pause; claimed or in-flight root or child effects must settle or be recovered first. */
  pause(id:string):Promise<WorkflowTreeSnapshot>;
  /** Resume scheduling only; unresolved approvals and child waits remain unresolved. */
  resume(id:string):Promise<WorkflowTreeSnapshot>;
  /**
   * Plan (dryRun) or apply a reviewed migration of a paused tree. Root steps with a prepared job and child steps with an
   * admitted child keep their exact definition; everything else follows the plan. The tree stays paused.
   */
  migrate(migration:WorkflowMigration<AnyWorkflowTree,AnyWorkflowTree>,command:MigrationCommand):Promise<WorkflowMigrationResult<WorkflowTreeSnapshot>>;
  recoverExpired(id:string):Promise<WorkflowTreeSnapshot>;
  events(id:string,after?:number):ReturnType<WorkflowTreeAggregateStore['events']>;
  close():Promise<void>;
  /** Admit no new wave, let admitted root/child effects and receipts settle within the deadline, then close. */
  drain(options?:WorkflowDrainOptions):Promise<WorkflowDrainReport>;
}

const terminal=new Set(['succeeded','failed','blocked','cancelled','outcome_unknown']);
const methods=(['initialize','submit','inspect','requestRootApproval','approveRootTool','prepareRootTool','claimPreparedRootTool','renewClaimedRootTool','startClaimedRootTool','recordRootToolReceipt','completeRootTool','inspectChild','admitChild','requestChildApproval','approveChildTool','prepareChildTool','claimPreparedChildTool','renewClaimedChildTool','startClaimedChildTool','recordChildToolReceipt','completeChildTool','finalizeChild','joinChild','finalizeRoot','cancelChild','cancelRoot','recoverExpired'] as const) satisfies readonly (keyof WorkflowTreeStore)[];

async function bounded<T>(operation:()=>Promise<T>,timeoutMs:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([Promise.resolve().then(operation),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new MayuraError('TIMEOUT','Workflow-tree validation or storage operation timed out.')),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}
function safe(value:unknown,maxBytes:number,label:string):JsonValue{try{return jsonValue(value,{maxBytes});}catch{throw new MayuraError('INVALID_INPUT',`Workflow-tree ${label} exceeds its bounded JSON contract.`);}}
function outputs(record:StoredRecord):Record<string,JsonValue>{const state=workflowTreeState(record);return Object.fromEntries(Object.entries(state.steps).filter(([,step])=>step.status==='succeeded').map(([id,step])=>[id,step.output]));}
function publicSnapshot(value:StoredTreeSnapshot):WorkflowTreeSnapshot{const state=workflowTreeState(value.record);return freezeJson(jsonValue({id:value.rootId,version:value.record.version,status:state.status,steps:state.steps,output:state.output,budget:value.budget})) as unknown as WorkflowTreeSnapshot;}
function publicChild(record:StoredRecord):WorkflowTreeChildSnapshot{const state=workflowTreeState(record);return freezeJson(jsonValue({id:record.id,version:record.version,status:state.status,steps:state.steps,output:state.output})) as unknown as WorkflowTreeChildSnapshot;}
function storageFailure(error:unknown):never{if(error instanceof StorageError&&['CONFLICT','NOT_FOUND','STALE_CLAIM','LIMIT_EXCEEDED'].includes(error.storageCode))throw error;throw new MayuraError('STORAGE_UNAVAILABLE','Workflow-tree storage is unavailable; reconcile uncertain actions before retrying.');}

/** Finite format-4 driver for root-local tools and one-level required children. */
export function createWorkflowTreeRuntime(options:WorkflowTreeRuntimeOptions):WorkflowTreeRuntime{
  let api:WorkflowTreeStore;try{if(!options.store?.workflowTrees||methods.some(method=>typeof options.store.workflowTrees[method]!=='function'))throw new Error();api=Object.freeze(Object.fromEntries(methods.map(method=>[method,options.store.workflowTrees[method].bind(options.store.workflowTrees)]))) as unknown as WorkflowTreeStore;}catch{throw new MayuraError('UNSUPPORTED_PROFILE','This adapter does not provide the optional workflow-tree capability.');}
  // Optional pause controls: custom adapters without them keep working until pause is requested.
  const trees=options.store.workflowTrees;const controls={pauseRoot:typeof trees.pauseRoot==='function'?trees.pauseRoot.bind(trees):undefined,resumeRoot:typeof trees.resumeRoot==='function'?trees.resumeRoot.bind(trees):undefined,migrateRoot:typeof trees.migrateRoot==='function'?trees.migrateRoot.bind(trees):undefined};
  const authority=workflowTreePolicy({scope:options.scope,permissions:options.permissions?.allow,policyVersion:options.policyVersion,maxCostMicros:options.maxCostMicros,maxCalls:options.maxCalls,maxOutputBytes:options.maxOutputBytes??65_536,approvalTtlMs:options.approvalTtlMs??3_600_000});
  if(typeof options.workerId!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$/.test(options.workerId))throw new MayuraError('INVALID_CONFIG','A bounded workflow-tree worker identity is required.');const leaseMs=options.leaseMs??3_000;const timeoutMs=options.storageTimeoutMs??10_000;const maxConcurrentJobs=options.maxConcurrentJobs??4;const maxConcurrentRuns=options.maxConcurrentRuns??16;for(const [name,value] of Object.entries({leaseMs,timeoutMs,maxConcurrentJobs,maxConcurrentRuns}))assertPositiveInteger(value,name);if(leaseMs<1_000||leaseMs>300_000||timeoutMs>30_000||maxConcurrentJobs>32||maxConcurrentRuns>128)throw new MayuraError('INVALID_CONFIG','Workflow-tree worker limits exceed supported bounds.');
  const scopeKey=digest('mayura:scope:v1',authority.scope);const policyHash=digest('mayura:workflow-tree-policy:v1',authority);let initialized:Promise<void>|undefined;let closed=false;let closing:Promise<void>|undefined;let slots=0;const active=new Map<string,AbortController>();const runs=new Map<string,{definition:AnyWorkflowTree;operation:Promise<WorkflowTreeSnapshot>}>();const pendingExecutions=new Set<Promise<void>>();const gate=createWorkflowDrainGate();
  const open=():void=>{if(closed)throw new MayuraError('CANCELLED','Workflow-tree runtime is closed.');};const initialize=()=>initialized??=(async()=>{try{await bounded(()=>api.initialize(),timeoutMs);}catch(error){storageFailure(error);}})();const access=(id:string)=>{if(typeof id!=='string'||!/^[a-f0-9]{64}$/.test(id))throw new MayuraError('INVALID_INPUT','Workflow-tree run ID must be an exact hash.');return{scope:scopeKey,rootId:id,rootPolicyHash:policyHash};};
  const call=async<T>(operation:()=>Promise<T>):Promise<T>=>{try{return await bounded(operation,timeoutMs);}catch(error){return storageFailure(error);}};
  const inspectStored=async(id:string):Promise<StoredTreeSnapshot>=>{open();await initialize();const value=await call(()=>api.inspect(access(id)));if(!value)throw new MayuraError('NOT_FOUND','Workflow tree was not found in this scope.');if(value.rootId!==id||value.record.scope!==scopeKey||value.policyHash!==policyHash)throw new MayuraError('CONFLICT','Stored workflow-tree identity does not match this runtime.');workflowTreeState(value.record);return value;};
  const supported=(definition:AnyWorkflowTree):void=>{assertWorkflowTree(definition);for(const child of definition.nodes.filter(node=>node.kind==='child'))assertWorkflow(child.workflow);};
  const matchRoot=(definition:AnyWorkflowTree,root:StoredTreeSnapshot):void=>{if(root.manifestHash!==definition.digest||workflowTreeState(root.record).definition!==definition.digest)throw new MayuraError('CONFLICT','Stored workflow tree uses a different genuine definition.');};
  const receiptId=(jobId:string,fence:number,receipt:ExecutionReceipt)=>digest('mayura:workflow-tree-receipt:v1',{jobId,fence,receipt});
  const reserveJobSlot=()=>{if(slots>=maxConcurrentJobs)return undefined;slots++;let resolveDrain!:()=>void;const drain=new Promise<void>(resolve=>{resolveDrain=resolve;});pendingExecutions.add(drain);let acquired=false;let handlerSettled=false;let logicalSettled=false;let released=false;const release=()=>{if(!released&&logicalSettled&&(!acquired||handlerSettled)){released=true;slots--;pendingExecutions.delete(drain);resolveDrain();}};return{acquire:async(signal:AbortSignal)=>{signal.throwIfAborted();acquired=true;return()=>{handlerSettled=true;release();};},logical:()=>{logicalSettled=true;release();}};};

  async function executeRootTool(rootId:string,node:Extract<WorkflowNode,{kind:'tool'}>,record:StoredRecord,raw:JsonValue):Promise<{operation:()=>Promise<void>}|undefined>{
    const capacity=reserveJobSlot();if(!capacity)return undefined;const base={...access(rootId),nodeId:node.id};try{try{await call(()=>api.prepareRootTool({...base,expectedVersion:record.version,input:raw}));}catch(error){if(error instanceof StorageError&&error.storageCode==='CONFLICT'){capacity.logical();return undefined;}throw error;}const claimed=await call(()=>api.claimPreparedRootTool({...base,workerId:options.workerId,leaseMs}));if(!claimed){capacity.logical();return undefined;}const operation=async()=>{if(closed){capacity.logical();return;}let token:Claim=claimed.claim;let renewal:ReturnType<typeof setTimeout>|undefined;let renewing:Promise<void>|undefined;let finished=false;const controller=new AbortController();active.set(claimed.job.jobId,controller);
      const schedule=()=>{if(finished||controller.signal.aborted)return;renewal=setTimeout(()=>{renewing=call(()=>api.renewClaimedRootTool({...base,claim:token,leaseMs})).then(result=>{token=result.claim;schedule();}).catch(()=>controller.abort());},Math.max(100,Math.floor(leaseMs/3)));};const stop=async()=>{finished=true;if(renewal)clearTimeout(renewal);await renewing;};let evidenceId:string|undefined;
      try{const result=await invokeTool(node.tool,raw,{runId:rootId,callId:`${rootId}/step:${node.id}`,scope:authority.scope,permissions:Object.freeze({allow:authority.permissions}),signal:controller.signal,budget:new Budget(node.tool.costMicros,1),maxOutputBytes:authority.maxOutputBytes,acquireExecution:capacity.acquire,beforeDispatch:async input=>{for(let attempt=0;attempt<32;attempt++){const current=await inspectStored(rootId);try{const started=await call(()=>api.startClaimedRootTool({...base,expectedVersion:current.record.version,claim:token,input}));if(started.status!=='started')throw new MayuraError('CONFLICT','The root claim does not grant a fresh dispatch.');schedule();return;}catch(error){if(!(error instanceof StorageError&&error.storageCode==='CONFLICT'))throw error;}}throw new MayuraError('CONFLICT','Root start contention exceeded its bounded retry limit.');},onExecutionReceipt:async receipt=>{const withheld=Object.freeze({...receipt,disclosure:'withheld' as const});const currentEvidence=receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordRootToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));}});if(!result.receipt)return;const withheld=Object.freeze({...result.receipt,disclosure:'withheld' as const});const currentEvidence=evidenceId??receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordRootToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));if(withheld.execution==='unknown')return;await stop();const outcome=result.status==='succeeded'?'succeeded':withheld.execution==='failed'?'failed':'blocked';await call(()=>api.completeRootTool({...base,claim:token,commandId:crypto.randomUUID(),evidenceId:currentEvidence,outcome,output:result.status==='succeeded'?safe(result.output,authority.maxOutputBytes,'tool output'):null}));}catch(error){if(!(error instanceof StorageError&&['STALE_CLAIM','CONFLICT'].includes(error.code)))throw error;}finally{await stop();active.delete(claimed.job.jobId);capacity.logical();}
    };return{operation};}catch(error){capacity.logical();throw error;}
  }

  async function executeTool(rootId:string,childId:string,childPolicyHash:string,childPermissions:readonly string[],maxOutputBytes:number,node:Extract<WorkflowNode,{kind:'tool'}>,record:StoredRecord,raw:JsonValue):Promise<{operation:()=>Promise<void>}|undefined>{
    const capacity=reserveJobSlot();if(!capacity)return undefined;const base={...access(rootId),childId,childPolicyHash,nodeId:node.id};try{try{await call(()=>api.prepareChildTool({...base,expectedVersion:record.version,input:raw}));}catch(error){if(error instanceof StorageError&&error.storageCode==='CONFLICT'){capacity.logical();return undefined;}throw error;}const claimed=await call(()=>api.claimPreparedChildTool({...base,workerId:options.workerId,leaseMs}));if(!claimed){capacity.logical();return undefined;}const operation=async()=>{if(closed){capacity.logical();return;}let token:Claim=claimed.claim;let renewal:ReturnType<typeof setTimeout>|undefined;let renewing:Promise<void>|undefined;let finished=false;const controller=new AbortController();active.set(claimed.job.jobId,controller);
      const schedule=()=>{if(finished||controller.signal.aborted)return;renewal=setTimeout(()=>{renewing=call(()=>api.renewClaimedChildTool({...base,claim:token,leaseMs})).then(result=>{token=result.claim;schedule();}).catch(()=>controller.abort());},Math.max(100,Math.floor(leaseMs/3)));};const stop=async()=>{finished=true;if(renewal)clearTimeout(renewal);await renewing;};let evidenceId:string|undefined;
      try{const result=await invokeTool(node.tool,raw,{runId:childId,callId:`${childId}/step:${node.id}`,scope:authority.scope,permissions:Object.freeze({allow:childPermissions}),signal:controller.signal,budget:new Budget(node.tool.costMicros,1),maxOutputBytes,acquireExecution:capacity.acquire,beforeDispatch:async input=>{for(let attempt=0;attempt<32;attempt++){const current=await call(()=>api.inspectChild({...access(rootId),childId,childPolicyHash}));try{const started=await call(()=>api.startClaimedChildTool({...base,expectedVersion:current.member.version,claim:token,input}));if(started.status!=='started')throw new MayuraError('CONFLICT','The child claim does not grant a fresh dispatch.');schedule();return;}catch(error){if(!(error instanceof StorageError&&error.storageCode==='CONFLICT'))throw error;}}throw new MayuraError('CONFLICT','Child start contention exceeded its bounded retry limit.');},onExecutionReceipt:async receipt=>{const withheld=Object.freeze({...receipt,disclosure:'withheld' as const});const currentEvidence=receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordChildToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));}});if(!result.receipt)return;const withheld=Object.freeze({...result.receipt,disclosure:'withheld' as const});const currentEvidence=evidenceId??receiptId(claimed.job.jobId,claimed.claim.fence,withheld);evidenceId=currentEvidence;await call(()=>api.recordChildToolReceipt({...base,fence:claimed.claim.fence,evidenceId:currentEvidence,receipt:withheld}));if(withheld.execution==='unknown')return;await stop();const outcome=result.status==='succeeded'?'succeeded':withheld.execution==='failed'?'failed':'blocked';await call(()=>api.completeChildTool({...base,claim:token,commandId:crypto.randomUUID(),evidenceId:currentEvidence,outcome,output:result.status==='succeeded'?safe(result.output,maxOutputBytes,'tool output'):null}));}catch(error){if(!(error instanceof StorageError&&['STALE_CLAIM','CONFLICT'].includes(error.code)))throw error;}finally{await stop();active.delete(claimed.job.jobId);capacity.logical();}
    };return{operation};}catch(error){capacity.logical();throw error;}
  }

  async function drive(definition:AnyWorkflowTree,id:string):Promise<WorkflowTreeSnapshot>{
    const rootNodes=definition.nodes.filter((node):node is Extract<WorkflowNode,{kind:'tool'}>=>node.kind==='tool');const childNodes=definition.nodes.filter(node=>node.kind==='child');for(let wave=0;wave<256;wave++){open();let root=await inspectStored(id);matchRoot(definition,root);let rootState=workflowTreeState(root.record);if(rootState.status==='paused')return publicSnapshot(root);if(terminal.has(rootState.status)){if(rootState.status!=='succeeded'&&!root.budget.accounts.find(account=>account.id==='root')?.closed)root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}const release=gate.enter();if(!release)return publicSnapshot(root);try{let progress=false;const operations:(()=>Promise<void>)[]=[];const recovery=await call(()=>api.recoverExpired({...access(id),limit:128}));if(recovery.jobs.length){root=recovery.root;rootState=workflowTreeState(root.record);progress=true;}if(rootState.status==='paused')return publicSnapshot(root);
      for(const node of rootNodes){root=await inspectStored(id);rootState=workflowTreeState(root.record);const step=rootState.steps[node.id];if(!step||terminal.has(rootState.status)||!['pending','waiting','approved'].includes(step.status)||node.dependsOn?.some(dependency=>rootState.steps[dependency]?.status!=='succeeded'))continue;const required=[`tool:${node.tool.id}`,...node.tool.capabilities,...(node.tool.effects==='none'?[]:[`effect:${node.tool.effects}`])];if(required.some(grant=>!authority.permissions.includes(grant))){root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}let input:JsonValue;try{const raw=resolveBinding(node.input,rootState.input,outputs(root.record));input=safe(await validate(node.tool.input,raw,'input',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'tool input');}catch{root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}if(node.approval){const previousVersion=root.record.version;root=await call(()=>api.requestRootApproval({...access(id),nodeId:node.id,expectedVersion:previousVersion,input}));rootState=workflowTreeState(root.record);progress=root.record.version!==previousVersion||progress;if(rootState.steps[node.id]?.status!=='approved')continue;}const scheduled=await executeRootTool(id,node,root.record,input);if(scheduled){operations.push(scheduled.operation);progress=true;}}
      for(const childNode of childNodes){root=await inspectStored(id);rootState=workflowTreeState(root.record);const rootStep=rootState.steps[childNode.id];if(!rootStep||terminal.has(rootState.status))break;if(!rootStep.child&&childNode.dependsOn?.some(dependency=>rootState.steps[dependency]?.status!=='succeeded'))continue;let childRecord:StoredRecord;let childId:string;let childPolicyHash:string;if(!rootStep.child){const raw=resolveBinding(childNode.input,rootState.input,outputs(root.record));const input=safe(await validate(childNode.workflow.input,raw,'input',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'child input');const admitted=await call(()=>api.admitChild({...access(id),parentId:id,nodeId:childNode.id,expectedVersion:root.record.version,input}));root=admitted.root;childRecord=admitted.child;childId=admitted.childId;childPolicyHash=admitted.policyHash;progress||=admitted.created;}else{childId=rootStep.child.runId;childPolicyHash=rootStep.child.policyHash;childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;}
        let childState=workflowTreeState(childRecord);if(!terminal.has(childState.status)){for(const node of childNode.workflow.nodes){if(node.kind!=='tool')continue;childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;childState=workflowTreeState(childRecord);const step=childState.steps[node.id];if(!step||!['pending','waiting','approved'].includes(step.status)||node.dependsOn?.some(dependency=>childState.steps[dependency]?.status!=='succeeded'))continue;const required=[`tool:${node.tool.id}`,...node.tool.capabilities,...(node.tool.effects==='none'?[]:[`effect:${node.tool.effects}`])];if(required.some(grant=>!childNode.policy.permissions.includes(grant))){const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));childRecord=cancelled.member;progress=true;break;}let input:JsonValue;try{const raw=resolveBinding(node.input,childState.input,outputs(childRecord));input=safe(await validate(node.tool.input,raw,'input',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'tool input');}catch{const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));childRecord=cancelled.member;progress=true;break;}if(node.approval){const previousVersion=childRecord.version;const requested=await call(()=>api.requestChildApproval({...access(id),childId,childPolicyHash,nodeId:node.id,expectedVersion:previousVersion,input}));childRecord=requested.member;childState=workflowTreeState(childRecord);progress=childRecord.version!==previousVersion||progress;if(childState.steps[node.id]?.status!=='approved')continue;}const scheduled=await executeTool(id,childId,childPolicyHash,childNode.policy.permissions,childNode.policy.maxOutputBytes,node,childRecord,input);if(scheduled){operations.push(scheduled.operation);progress=true;}}
          childRecord=(await call(()=>api.inspectChild({...access(id),childId,childPolicyHash}))).member;childState=workflowTreeState(childRecord);if(!terminal.has(childState.status)&&Object.values(childState.steps).every(step=>step.status==='succeeded')){let output:JsonValue|undefined;try{const raw=resolveBinding(childNode.workflow.result,childState.input,outputs(childRecord));output=safe(await validate(childNode.workflow.output,raw,'output',{maxBytes:childNode.policy.maxOutputBytes}),childNode.policy.maxOutputBytes,'child output');}catch{const cancelled=await call(()=>api.cancelChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,commandId:crypto.randomUUID()}));root=cancelled.root;childRecord=cancelled.member;progress=true;}if(output!==undefined){const finalized=await call(()=>api.finalizeChild({...access(id),childId,childPolicyHash,expectedVersion:childRecord.version,output}));root=finalized.root;childRecord=finalized.member;progress=true;}}
        }
        childState=workflowTreeState(childRecord);root=await inspectStored(id);rootState=workflowTreeState(root.record);if(terminal.has(childState.status)&&rootState.steps[childNode.id]?.child?.joinedVersion===null){root=await call(()=>api.joinChild({...access(id),nodeId:childNode.id,expectedVersion:root.record.version}));progress=true;if(workflowTreeState(root.record).status!=='succeeded'&&terminal.has(workflowTreeState(root.record).status)){root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}}
      }
      if(operations.length){const results=await Promise.allSettled(operations.map(operation=>operation()));const failure=results.find(result=>result.status==='rejected');if(failure?.status==='rejected')throw failure.reason;continue;}
      root=await inspectStored(id);rootState=workflowTreeState(root.record);if(rootState.status==='paused')return publicSnapshot(root);if(Object.values(rootState.steps).every(step=>step.status==='succeeded')){let output:JsonValue;try{const raw=resolveBinding(definition.result,rootState.input,outputs(root.record));output=safe(await validate(definition.output,raw,'output',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'root output');}catch{root=(await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root;return publicSnapshot(root);}root=await call(()=>api.finalizeRoot({...access(id),expectedVersion:root.record.version,output}));return publicSnapshot(root);}
      if(!progress)return publicSnapshot(root);
    }finally{release();}}throw new MayuraError('LIMIT_EXCEEDED','Workflow-tree continuation exceeded its finite progress bound.');
  }

  const closeRuntime=():Promise<void>=>{if(!closing){closed=true;for(const controller of active.values())controller.abort();closing=(async()=>{await Promise.allSettled([...runs.values()].map(run=>run.operation));await Promise.allSettled([...pendingExecutions]);})();}return closing;};
  return Object.freeze<WorkflowTreeRuntime>({
    profile:'scheduled-v3',
    async submit(definition,command){open();supported(definition);if(typeof command.idempotencyKey!=='string'||!command.idempotencyKey.length||command.idempotencyKey.length>128)throw new MayuraError('INVALID_INPUT','A bounded stable submission key is required.');const raw=safe(command.input,authority.maxOutputBytes,'input');const input=safe(await validate(definition.input,raw,'input',{maxBytes:authority.maxOutputBytes}),authority.maxOutputBytes,'input');await initialize();const result=await call(()=>api.submit({manifest:treeManifest(definition),policy:authority,resources:{},input,idempotencyKey:command.idempotencyKey}));matchRoot(definition,result.snapshot);return publicSnapshot(result.snapshot);},
    async inspect(id){return publicSnapshot(await inspectStored(id));},
    async inspectChild(id,childId){const root=await inspectStored(id);if(!/^[a-f0-9]{64}$/.test(childId))throw new MayuraError('INVALID_INPUT','Child run ID must be an exact hash.');const link=Object.values(workflowTreeState(root.record).steps).find(step=>step.child?.runId===childId)?.child;if(!link)throw new MayuraError('CONFLICT','Child is not owned by this workflow tree.');return publicChild((await call(()=>api.inspectChild({...access(id),childId,childPolicyHash:link.policyHash}))).member);},
    runUntilSettled(definition,id){open();if(gate.draining)return Promise.reject(new MayuraError('CANCELLED','Workflow-tree runtime is draining.'));supported(definition);access(id);const existing=runs.get(id);if(existing)return existing.definition===definition?existing.operation:Promise.reject(new MayuraError('CONFLICT','The active driver uses a different workflow-tree definition.'));if(runs.size>=maxConcurrentRuns)return Promise.reject(new MayuraError('LIMIT_EXCEEDED','This workflow-tree worker has reached its active-run limit.'));const operation=drive(definition,id).catch(async(error:unknown)=>{if(error instanceof StorageError&&error.storageCode==='CONFLICT'){const current=await inspectStored(id);if(workflowTreeState(current.record).status==='paused')return publicSnapshot(current);}throw error;}).finally(()=>runs.delete(id));runs.set(id,{definition,operation});return operation;},
    async approve(command){
      open();const root=await inspectStored(command.id);if((command.childId!==undefined&&!/^[a-f0-9]{64}$/.test(command.childId))||!/^[A-Za-z][A-Za-z0-9._-]{0,127}$/.test(command.nodeId)||!/^[a-f0-9]{64}$/.test(command.digest))throw new MayuraError('INVALID_INPUT','Approval requires exact member, node and review identities.');if(!options.verifyHuman)throw new MayuraError('PERMISSION_DENIED','A trusted human verifier is required.');let human:VerifiedHuman;try{human=await bounded(()=>options.verifyHuman!(command.credential),30_000);if(typeof human.id!=='string'||!human.id.length||/[\uD800-\uDFFF]/u.test(human.id)||new TextEncoder().encode(human.id).length>256||human.id.includes('\u0000')||human.projectId!==authority.scope.projectId||human.canApprove!==true)throw new Error();}catch{throw new MayuraError('PERMISSION_DENIED','Human verification did not authorize this approval.');}
      if(command.childId===undefined){await call(()=>api.approveRootTool({...access(command.id),nodeId:command.nodeId,expectedVersion:root.record.version,digest:command.digest,humanId:human.id}));return publicSnapshot(await inspectStored(command.id));}
      const childId=command.childId;const state=workflowTreeState(root.record);const link=Object.values(state.steps).find(step=>step.child?.runId===childId)?.child;if(!link)throw new MayuraError('CONFLICT','Child is not owned by this workflow tree.');const child=await call(()=>api.inspectChild({...access(command.id),childId,childPolicyHash:link.policyHash}));await call(()=>api.approveChildTool({...access(command.id),childId,childPolicyHash:link.policyHash,nodeId:command.nodeId,expectedVersion:child.member.version,digest:command.digest,humanId:human.id}));return publicSnapshot(await inspectStored(command.id));
    },
    async cancel(id){const root=await inspectStored(id);if(workflowTreeState(root.record).status==='succeeded')return publicSnapshot(root);return publicSnapshot((await call(()=>api.cancelRoot({...access(id),expectedVersion:root.record.version,commandId:crypto.randomUUID()}))).root);},
    async pause(id){
      if(!controls.pauseRoot)throw new MayuraError('UNSUPPORTED_PROFILE','This adapter does not provide durable workflow-tree pause.');
      for(let attempt=0;attempt<32;attempt++){const root=await inspectStored(id);const status=workflowTreeState(root.record).status;if(status==='paused')return publicSnapshot(root);if(terminal.has(status))throw new MayuraError('CONFLICT','A terminal workflow tree cannot be paused.');
        try{return publicSnapshot(await call(()=>controls.pauseRoot!({...access(id),expectedVersion:root.record.version})));}
        catch(error){if(!(error instanceof StorageError&&error.storageCode==='CONFLICT'))throw error;if((await inspectStored(id)).record.version===root.record.version)throw new MayuraError('CONFLICT','A workflow tree with a claimed or in-flight effect cannot enter the quiescent paused state.');}}
      throw new MayuraError('CONFLICT','Workflow-tree pause contention exceeded its bounded retry limit.');
    },
    async resume(id){
      if(!controls.resumeRoot)throw new MayuraError('UNSUPPORTED_PROFILE','This adapter does not provide durable workflow-tree pause.');
      for(let attempt=0;attempt<32;attempt++){const root=await inspectStored(id);if(workflowTreeState(root.record).status!=='paused')throw new MayuraError('CONFLICT','Only a paused workflow tree can be resumed.');
        try{return publicSnapshot(await call(()=>controls.resumeRoot!({...access(id),expectedVersion:root.record.version})));}
        catch(error){if(!(error instanceof StorageError&&error.storageCode==='CONFLICT'))throw error;}}
      throw new MayuraError('CONFLICT','Workflow-tree resume contention exceeded its bounded retry limit.');
    },
    async migrate(migration,command){
      open();assertWorkflowMigration(migration);supported(migration.from);supported(migration.to);
      const {id,actorId,commandId,dryRun=false}=migrationCommand(command);
      const root=await inspectStored(id);matchRoot(migration.from,root);const state=workflowTreeState(root.record);
      const nodes=(definition:AnyWorkflowTree)=>treeManifest(definition).graph.map(node=>({id:node.id,kind:node.kind,dependsOn:node.dependsOn,fingerprint:nodeFingerprint(node as unknown as Record<string,unknown>),...(nodeEvidence(node)?{evidence:nodeEvidence(node)!}:{})}));
      const fromNodes=nodes(migration.from);const toNodes=nodes(migration.to);
      const preconditions:MigrationBlocker[]=[];
      if(state.status!=='paused')preconditions.push({node:'*',reason:`The tree is ${state.status}; pause it before migrating.`});
      if(runs.has(id))preconditions.push({node:'*',reason:'This worker is still driving the tree; wait for its driver to stop.'});
      // A prepared job or an admitted child is durable history keyed by node: it must survive unchanged under its own id.
      for(const [nodeId,step] of Object.entries(state.steps))if(step.candidateHash!==null||step.child!==null){
        const before=fromNodes.find(node=>node.id===nodeId);const after=toNodes.find(node=>node.id===nodeId);
        if(!after||before?.fingerprint!==after.fingerprint||Object.values(migration.renames).includes(nodeId))preconditions.push({node:nodeId,reason:`Step "${nodeId}" has execution history; it must be kept unchanged.`});
      }
      // An admitted child that has not joined is still in flight from the root's point of view.
      const status=(step:typeof state.steps[string]):string=>step.child!==null&&step.child.joinedVersion===null?'running':step.status;
      const plan=planWorkflowMigration({migration,format:'tree-v4',runId:id,fromDigest:migration.from.digest,toDigest:migration.to.digest,from:fromNodes,to:toNodes,
        steps:Object.entries(state.steps).map(([step,value])=>({id:step,status:status(value)})),preconditions});
      if(dryRun)return freezeJson(jsonValue({plan})) as unknown as WorkflowMigrationResult<WorkflowTreeSnapshot>;
      assertMigrationAllowed(plan);
      if(!controls.migrateRoot)throw new MayuraError('UNSUPPORTED_PROFILE','This adapter cannot migrate in-flight workflow trees.');
      const manifest=treeManifest(migration.to);
      const fresh=initialWorkflowTreeRootState(manifest,state.input,id,migration.to.digest,state.policy,authority);
      const carried:Record<string,unknown>={};
      for(const entry of plan.entries)if(entry.target)carried[entry.target]=entry.action==='keep'||entry.action==='accept'?state.steps[entry.source!]:fresh.steps[entry.target];
      const steps=Object.fromEntries(manifest.graph.map(node=>[node.id,carried[node.id]]));
      const next={...state,definition:migration.to.digest,steps,reservedMicros:Object.values(steps).reduce<number>((sum,step)=>sum+(step as {costReserved:number}).costReserved,0)};
      const migrated=await call(()=>controls.migrateRoot!({...access(id),expectedVersion:root.record.version,commandId,manifest,resources:{},state:jsonValue(next) as never,migrationId:migration.id,actorId}));
      matchRoot(migration.to,migrated);
      return freezeJson(jsonValue({plan,snapshot:publicSnapshot(migrated)})) as unknown as WorkflowMigrationResult<WorkflowTreeSnapshot>;
    },
    async recoverExpired(id){await inspectStored(id);return publicSnapshot((await call(()=>api.recoverExpired({...access(id),limit:128}))).root);},
    async events(id,after=0){open();access(id);if(!Number.isSafeInteger(after)||after<0)throw new MayuraError('INVALID_INPUT','A non-negative event cursor is required.');await inspectStored(id);return call(()=>options.store.events(scopeKey,id,after));},
    close:closeRuntime,
    drain(options){return gate.drain(options,closeRuntime);},
  });
}
