import { afterEach,describe,expect,it,vi } from 'vitest';
import { z } from 'zod';
import { defineTool } from '@mayura/tools';
import { createSqliteStore } from '@mayura/storage';
import { StorageError } from '@mayura/storage-contracts';
import { createWorkflowTreeCoordinator,createWorkflowTreeRuntime,defineWorkflowTree } from '../src/children.js';

const stores:ReturnType<typeof createSqliteStore>[]=[];const closers:{close():Promise<void>}[]=[];
afterEach(async()=>{await Promise.all(closers.splice(0).map(item=>item.close()));await Promise.all(stores.splice(0).map(store=>store.close()));});
const scope={principalId:'tree-coordinator',projectId:'project'};const permissions={allow:['tool:known','tool:unknown']} as const;
function tree(id:string,execute:(value:number)=>Promise<number>){const tool=defineTool({id,version:'1',description:`${id} tool`,input:z.number(),output:z.number(),effects:'none',capabilities:[],costMicros:1,execute});return defineWorkflowTree({id,version:'1',input:z.number(),output:z.number(),nodes:[{kind:'tool',id:'work',tool,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}});}

describe('workflow-tree coordinator',()=>{
  it('continues registered roots and reports unknown definitions without dispatch',async()=>{const store=createSqliteStore({filename:':memory:'});stores.push(store);await store.initialize();const knownExecute=vi.fn(async(value:number)=>value+1);const unknownExecute=vi.fn(async(value:number)=>value+10);const known=tree('known',knownExecute);const unknown=tree('unknown',unknownExecute);const shared={store,scope,permissions,policyVersion:'1',maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024} as const;const submitter=createWorkflowTreeRuntime({...shared,workerId:'submitter'});closers.push(submitter);const knownRun=await submitter.submit(known,{input:1,idempotencyKey:'known'});const unknownRun=await submitter.submit(unknown,{input:1,idempotencyKey:'unknown'});await submitter.close();closers.splice(closers.indexOf(submitter),1);const coordinator=createWorkflowTreeCoordinator({...shared,workerId:'coordinator',definitions:[known]});closers.push(coordinator);const report=await coordinator.runPage({limit:32});expect(report.status).toBe('completed');expect(report.examined).toBe(2);expect(report.outcomes).toEqual(expect.arrayContaining([{kind:'observed',rootId:knownRun.id,definitionHash:known.digest,version:expect.any(Number),status:'succeeded'},{kind:'skipped',rootId:unknownRun.id,definitionHash:unknown.digest,reason:'unregistered_definition'}]));expect(knownExecute).toHaveBeenCalledTimes(1);expect(unknownExecute).not.toHaveBeenCalled();const repeated=await coordinator.runPage({limit:32});expect(repeated).toMatchObject({status:'completed',examined:2,outcomes:[{kind:'skipped',rootId:unknownRun.id,reason:'unregistered_definition'}]});expect(knownExecute).toHaveBeenCalledTimes(1);});
  it('rejects duplicate or non-genuine catalogs before storage access',()=>{const store=createSqliteStore({filename:':memory:'});stores.push(store);const definition=tree('known',async value=>value);const shared={store,scope,permissions,policyVersion:'1',maxCostMicros:1,maxCalls:1,workerId:'worker'} as const;expect(()=>createWorkflowTreeCoordinator({...shared,definitions:[definition,definition]})).toThrow(expect.objectContaining({code:'INVALID_CONFIG'}));expect(()=>createWorkflowTreeCoordinator({...shared,definitions:[{...definition}] as never})).toThrow(expect.objectContaining({code:'INVALID_CONFIG'}));});
  it('interrupts a failed page with its original retry boundary and resumes safely',async()=>{const store=createSqliteStore({filename:':memory:'});stores.push(store);await store.initialize();const execute=vi.fn(async(value:number)=>value+1);const definition=tree('known',execute);const shared={scope,permissions,policyVersion:'1',maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024} as const;const submitter=createWorkflowTreeRuntime({store,...shared,workerId:'submitter'});closers.push(submitter);const runs=await Promise.all(['first','second'].map(id=>submitter.submit(definition,{input:1,idempotencyKey:id})));await submitter.close();closers.splice(closers.indexOf(submitter),1);const firstId=runs.map(run=>run.id).sort()[0]!;const broken={...store,workflowTrees:{...store.workflowTrees,inspect:async(command:Parameters<typeof store.workflowTrees.inspect>[0])=>{if(command.rootId===firstId)throw new StorageError('STORAGE_UNAVAILABLE','private detail');return store.workflowTrees.inspect(command);}}};const interrupted=createWorkflowTreeCoordinator({store:broken,...shared,workerId:'broken',definitions:[definition]});closers.push(interrupted);const failed=await interrupted.runPage({limit:32});expect(failed).toMatchObject({status:'interrupted',examined:2,retryCursor:null,code:'STORAGE_UNAVAILABLE',outcomes:[{kind:'failed',rootId:firstId,code:'STORAGE_UNAVAILABLE'},{kind:'not_attempted'}]});expect(execute).not.toHaveBeenCalled();await interrupted.close();closers.splice(closers.indexOf(interrupted),1);const healthy=createWorkflowTreeCoordinator({store,...shared,workerId:'healthy',definitions:[definition]});closers.push(healthy);const recovered=await healthy.runPage({limit:32});expect(recovered.status).toBe('completed');expect(recovered.outcomes.filter(outcome=>outcome.kind==='observed'&&outcome.status==='succeeded')).toHaveLength(2);expect(execute).toHaveBeenCalledTimes(2);});
});
