import { fork, type ChildProcess } from 'node:child_process';
import { mkdtemp, readFile, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { WorkflowTreeChildSnapshot, WorkflowTreeSnapshot } from '../src/children.js';

type Scenario='approval'|'dispatch'|'receipt'|'root-prepare'|'root-completion'|'root-finalization'|'root-cancellation'|'child-approval'|'child-dispatch'|'child-receipt'|'child-admission'|'child-prepare'|'child-completion'|'child-finalization'|'child-join';
interface Marker {readonly kind:'waiting'|'dispatched'|'receipt_pending'|'commit_pending'|'completed'|'fixture_error';readonly operation?:string;readonly runId?:string;readonly childId?:string;readonly digest?:string;readonly code?:string;readonly phase?:string;readonly before?:WorkflowTreeSnapshot;readonly memberBefore?:WorkflowTreeChildSnapshot;readonly snapshot?:WorkflowTreeSnapshot;readonly member?:WorkflowTreeChildSnapshot;readonly repeated?:WorkflowTreeSnapshot;readonly events?:readonly {readonly sequence:number;readonly type:string;readonly data:Readonly<Record<string,unknown>>}[]}
const fixturePath=fileURLToPath(new URL('./fixtures/workflow-tree-process-recovery.mjs',import.meta.url));
const tempPrefix='mayura-tree-process-recovery-';

// Child processes start Node.js and open SQLite: several times slower on hosted Windows CI runners (see vitest.config.ts),
// where a marker once took longer than 10 s. Other runs keep the tight limits.
const slowRunner=process.env['CI']==='true'&&process.platform==='win32';
async function within<T>(promise:Promise<T>,label:string,timeoutMs=slowRunner?30_000:10_000):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new Error(`Timed out waiting for ${label}.`)),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}

class FixtureProcess{
  readonly #child:ChildProcess;readonly #messages:Marker[]=[];readonly #listeners=new Set<()=>void>();readonly #exited:Promise<{code:number|null;signal:NodeJS.Signals|null}>;#exitObserved=false;#failure:Error|undefined;#stderr='';
  constructor(args:readonly string[]){this.#child=fork(fixturePath,[...args],{execArgv:[],stdio:['ignore','ignore','pipe','ipc']});this.#child.stderr?.on('data',(chunk:Buffer)=>{this.#stderr=`${this.#stderr}${chunk.toString()}`.slice(-4_096);});this.#child.on('message',(message:Marker)=>{this.#messages.push(message);if(message.kind==='fixture_error')this.#failure=new Error(`Child fixture failed (${message.code??'unknown'}) at ${message.phase??'unknown'}. ${this.#stderr}`);for(const listener of this.#listeners)listener();});this.#exited=new Promise((resolveExit,rejectExit)=>{this.#child.once('error',error=>{this.#failure=error;this.#exitObserved=true;rejectExit(error);for(const listener of this.#listeners)listener();});this.#child.once('exit',(code,signal)=>{this.#exitObserved=true;resolveExit({code,signal});for(const listener of this.#listeners)listener();});});void this.#exited.catch(()=>{});}
  async marker(kind:Marker['kind']):Promise<Marker>{let listener:(()=>void)|undefined;try{return await within(new Promise<Marker>((resolveMarker,reject)=>{listener=()=>{const found=this.#messages.find(message=>message.kind===kind);if(found)resolveMarker(found);else if(this.#failure)reject(this.#failure);else if(this.#exitObserved)reject(new Error(`Child exited before ${kind}. ${this.#stderr}`));};this.#listeners.add(listener);listener();}),`child marker ${kind}`);}finally{if(listener)this.#listeners.delete(listener);}}
  async successfulExit():Promise<void>{expect(await within(this.#exited,'successful child exit')).toEqual({code:0,signal:null});}
  async kill():Promise<void>{const pid=this.#child.pid;if(!this.#exitObserved&&pid!==undefined)process.kill(pid,'SIGKILL');await within(this.#exited,'owned child termination').catch(error=>{if(!this.#failure)throw error;});}
}

describe('real process termination and SQLite workflow-tree recovery',()=>{
  let directory:string;let children:FixtureProcess[];
  beforeEach(async()=>{directory=await mkdtemp(join(await realpath(tmpdir()),tempPrefix));children=[];});
  afterEach(async()=>{await Promise.all(children.map(child=>child.kill()));const actual=await realpath(directory);const temporaryRoot=await realpath(tmpdir());if(dirname(actual)!==temporaryRoot||!basename(actual).startsWith(tempPrefix)||resolve(directory)!==resolve(actual))throw new Error('Refusing cleanup outside the verified test-owned temporary directory.');await rm(actual,{recursive:true,force:true});});
  const spawn=(scenario:Scenario,action:'start'|'recover',runId?:string,digest?:string)=>{const child=new FixtureProcess([scenario,action,directory,...(runId?[runId]:[]),...(digest?[digest]:[])]);children.push(child);return child;};
  async function effects(){try{const contents=await readFile(join(directory,'effects.ndjson'),'utf8');return contents.trim().split('\n').filter(Boolean).map(line=>JSON.parse(line) as {runId:string;callId:string});}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return[];throw error;}}

  it('survives termination at root approval and executes the effect once after restart',async()=>{const first=spawn('approval','start');const waiting=await first.marker('waiting');expect(waiting.snapshot?.status).toBe('waiting');expect(waiting.digest).toBeTypeOf('string');expect(await effects()).toEqual([]);await first.kill();const second=spawn('approval','recover',waiting.runId!,waiting.digest!);const completed=await second.marker('completed');await second.successfulExit();const review=completed.before?.steps['write']?.approval as {digest?:unknown}|null;expect(review?.digest).toBe(waiting.digest);expect(completed.snapshot).toMatchObject({status:'succeeded',output:{value:7},steps:{write:{approval:{humanId:'verified-reviewer'},receipt:{execution:'succeeded',disclosure:'released'}}}});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toEqual([{runId:waiting.runId,callId:`${waiting.runId}/step:write`}]);expect(completed.events?.filter(event=>event.type==='step.dispatching')).toHaveLength(1);},slowRunner?75_000:25_000);

  it('quarantines a killed in-flight root effect and never redispatches it',async()=>{const first=spawn('dispatch','start');const dispatched=await first.marker('dispatched');expect(await effects()).toHaveLength(1);await first.kill();const second=spawn('dispatch','recover',dispatched.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.before?.steps['write']).toMatchObject({status:'dispatching',receipt:null});expect(completed.snapshot?.status).toBe('outcome_unknown');expect(completed.snapshot?.steps['write']?.status).toBe('unknown');expect(completed.snapshot?.budget.accounts.find(account=>account.id==='root')).toMatchObject({spentMicros:0,reservedMicros:1,calls:1,closed:true});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toHaveLength(1);expect(completed.events?.filter(event=>event.type==='step.dispatching')).toHaveLength(1);},slowRunner?75_000:25_000);

  it('preserves a root success receipt after a guard-stage crash without replay',async()=>{const first=spawn('receipt','start');const receipt=await first.marker('receipt_pending');expect(await effects()).toHaveLength(1);await first.kill();const second=spawn('receipt','recover',receipt.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.before?.steps['write']).toMatchObject({status:'dispatching',receipt:{execution:'succeeded',disclosure:'withheld'}});expect(completed.snapshot).toMatchObject({status:'blocked',output:null,steps:{write:{status:'blocked',output:null,receipt:{execution:'succeeded',disclosure:'withheld'}}}});expect(completed.snapshot?.budget.accounts.find(account=>account.id==='root')).toMatchObject({spentMicros:1,reservedMicros:0,calls:1,closed:true});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toHaveLength(1);expect(completed.events?.filter(event=>event.type==='job.receipt_recorded')).toHaveLength(1);expect(completed.events?.filter(event=>event.type==='step.dispatching')).toHaveLength(1);},slowRunner?75_000:25_000);

  it('survives termination at child approval and executes the child effect once after restart',async()=>{const first=spawn('child-approval','start');const waiting=await first.marker('waiting');expect(waiting.snapshot?.status).toBe('waiting');expect(waiting.childId).toBeTypeOf('string');expect(await effects()).toEqual([]);await first.kill();const second=spawn('child-approval','recover',waiting.runId!,waiting.digest!);const completed=await second.marker('completed');await second.successfulExit();const review=completed.memberBefore?.steps['write']?.approval as {digest?:unknown}|null;expect(review?.digest).toBe(waiting.digest);expect(completed.snapshot).toMatchObject({status:'succeeded',output:{value:7},steps:{child:{status:'succeeded'}}});expect(completed.member).toMatchObject({status:'succeeded',output:{value:7},steps:{write:{approval:{humanId:'verified-reviewer'},receipt:{execution:'succeeded',disclosure:'released'}}}});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toEqual([{runId:waiting.childId,callId:`${waiting.childId}/step:write`}]);},slowRunner?75_000:25_000);

  it('quarantines a killed in-flight child effect and never redispatches it',async()=>{const first=spawn('child-dispatch','start');const dispatched=await first.marker('dispatched');expect(dispatched.childId).toBeTypeOf('string');expect(await effects()).toHaveLength(1);await first.kill();const second=spawn('child-dispatch','recover',dispatched.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.memberBefore?.steps['write']).toMatchObject({status:'dispatching',receipt:null});expect(completed.member).toMatchObject({status:'outcome_unknown',steps:{write:{status:'unknown'}}});expect(completed.snapshot?.status).toBe('outcome_unknown');expect(completed.snapshot?.steps['child']?.status).toBe('unknown');const account=completed.snapshot?.budget.accounts.find(item=>item.id!=='root');expect(account).toMatchObject({spentMicros:0,reservedMicros:1,calls:1,closed:false});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toHaveLength(1);},slowRunner?75_000:25_000);

  it('preserves a child success receipt after a guard-stage crash without replay',async()=>{const first=spawn('child-receipt','start');const receipt=await first.marker('receipt_pending');expect(receipt.childId).toBeTypeOf('string');expect(await effects()).toHaveLength(1);await first.kill();const second=spawn('child-receipt','recover',receipt.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.memberBefore?.steps['write']).toMatchObject({status:'dispatching',receipt:{execution:'succeeded',disclosure:'withheld'}});expect(completed.member).toMatchObject({status:'blocked',output:null,steps:{write:{status:'blocked',output:null,receipt:{execution:'succeeded',disclosure:'withheld'}}}});expect(completed.snapshot).toMatchObject({status:'blocked',output:null,steps:{child:{status:'blocked'}}});const account=completed.snapshot?.budget.accounts.find(item=>item.id!=='root');expect(account).toMatchObject({spentMicros:1,reservedMicros:0,calls:1,closed:true});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toHaveLength(1);expect(completed.events?.filter(event=>event.type==='workflow.child_joined')).toHaveLength(1);},slowRunner?75_000:25_000);

  it.each([
    ['root-completion','completeRootTool',1,1],
    ['root-finalization','finalizeRoot',1,1],
    ['root-prepare','prepareRootTool',0,1],
    ['child-admission','admitChild',0,0],
    ['child-prepare','prepareChildTool',0,0],
    ['child-completion','completeChildTool',1,0],
    ['child-finalization','finalizeChild',1,0],
    ['child-join','joinChild',1,0],
  ] as const)('resumes after losing the committed %s acknowledgement without replay',async(scenario,operation,effectsBeforeKill,rootDispatchEvents)=>{const first=spawn(scenario,'start');const committed=await first.marker('commit_pending');expect(committed.operation).toBe(operation);expect(await effects()).toHaveLength(effectsBeforeKill);await first.kill();const second=spawn(scenario,'recover',committed.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.snapshot).toMatchObject({status:'succeeded',output:{value:7}});expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toHaveLength(1);expect(completed.events?.filter(event=>event.type==='step.dispatching')).toHaveLength(rootDispatchEvents);},slowRunner?75_000:25_000);

  it('resumes after losing the committed root-cancellation acknowledgement',async()=>{const first=spawn('root-cancellation','start');const committed=await first.marker('commit_pending');expect(committed.operation).toBe('cancelRoot');expect(await effects()).toEqual([]);await first.kill();const second=spawn('root-cancellation','recover',committed.runId!);const completed=await second.marker('completed');await second.successfulExit();expect(completed.before?.status).toBe('cancelled');expect(completed.snapshot?.status).toBe('cancelled');expect(completed.repeated).toEqual(completed.snapshot);expect(await effects()).toEqual([]);expect(completed.events?.filter(event=>event.type==='run.cancelled')).toHaveLength(1);},slowRunner?75_000:25_000);
});
