import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { describe, expect, it } from 'vitest';
import { z } from 'zod';
import { defineTool } from '@mayura/tools';
import { createPostgresStore } from '@mayura/storage';
import { createWorkflowTreeRuntime, defineWorkflowTree } from '../src/children.js';
import { defineWorkflow } from '../src/definition.js';

const connectionString=process.env['MAYURA_TEST_POSTGRES_URL'];const suite=connectionString?describe:describe.skip;

suite('PostgreSQL workflow-tree developer runtime',()=>{
  it('executes and reopens a required child through the selected adapter',async()=>{
    const schema=`mayura_tree_runtime_${randomUUID().replaceAll('-','')}`;const open=()=>createPostgresStore({connectionString:connectionString!,schema});const stores=[open()];const runtimes:ReturnType<typeof createWorkflowTreeRuntime>[]=[];
    try{const execute=async(value:number)=>value+1;const tool=defineTool({id:'increment',version:'1',description:'Increment.',input:z.number(),output:z.number(),effects:'none',capabilities:[],costMicros:2,execute});const leaf=defineWorkflow({id:'leaf',version:'1',input:z.number(),output:z.number(),nodes:[{kind:'tool',id:'work',tool,input:{kind:'input',path:[]},approval:true}],result:{kind:'step',stepId:'work',path:[]}});const tree=defineWorkflowTree({id:'tree',version:'1',input:z.number(),output:z.number(),nodes:[{kind:'child',id:'child',workflow:leaf,input:{kind:'input',path:[]},policy:{permissions:['tool:increment'],maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:5_000},resources:{work:[]}}],result:{kind:'step',stepId:'child',path:[]}});const rootTree=defineWorkflowTree({id:'root-tree',version:'1',input:z.number(),output:z.number(),nodes:[leaf.nodes[0]!],result:{kind:'step',stepId:'work',path:[]}});const options={scope:{principalId:'runtime',projectId:'project'},permissions:{allow:['tool:increment']},policyVersion:'1',maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,workerId:'worker',verifyHuman:async()=>({id:'reviewer',projectId:'project',canApprove:true})} as const;await stores[0]!.initialize();const first=createWorkflowTreeRuntime({store:stores[0]!,...options});runtimes.push(first);const submitted=await first.submit(tree,{input:1,idempotencyKey:'root'});await first.close();runtimes.splice(0);const reopened=open();stores.push(reopened);await reopened.initialize();const second=createWorkflowTreeRuntime({store:reopened,...options});runtimes.push(second);const waiting=await second.runUntilSettled(tree,submitted.id);const link=waiting.steps['child']?.child;if(!link)throw new Error('fixture');const child=await second.inspectChild(waiting.id,link.runId);const approval=child.steps['work']?.approval as {digest?:unknown}|null;if(!approval||typeof approval.digest!=='string')throw new Error('fixture');await second.approve({id:waiting.id,childId:link.runId,nodeId:'work',digest:approval.digest,credential:'trusted'});const finished=await second.runUntilSettled(tree,submitted.id);expect(finished).toMatchObject({status:'succeeded',output:2});expect(await second.inspect(submitted.id)).toEqual(finished);const localSubmitted=await second.submit(rootTree,{input:2,idempotencyKey:'root-local'});const localWaiting=await second.runUntilSettled(rootTree,localSubmitted.id);const localApproval=localWaiting.steps['work']?.approval as {digest?:unknown}|null;if(!localApproval||typeof localApproval.digest!=='string')throw new Error('fixture');await second.approve({id:localWaiting.id,nodeId:'work',digest:localApproval.digest,credential:'trusted'});const localFinished=await second.runUntilSettled(rootTree,localWaiting.id);expect(localFinished).toMatchObject({status:'succeeded',output:3});
    }finally{await Promise.all(runtimes.map(runtime=>runtime.close()));await Promise.all(stores.map(store=>store.close()));if(!/^mayura_tree_runtime_[a-f0-9]{32}$/.test(schema))throw new Error('Unexpected fixture schema.');const pool=new Pool({connectionString:connectionString!});try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}
  });

  it('executes ready root and child branches within one shared bound',async()=>{
    const schema=`mayura_tree_runtime_${randomUUID().replaceAll('-','')}`;const store=createPostgresStore({connectionString:connectionString!,schema});const runtimes:ReturnType<typeof createWorkflowTreeRuntime>[]=[];
    try{await store.initialize();let active=0;let peak=0;let arrivals=0;let release!:()=>void;const bothStarted=new Promise<void>(resolve=>{release=resolve;});const tool=defineTool({id:'parallel-increment',version:'1',description:'Increment.',input:z.number(),output:z.number(),effects:'none',capabilities:[],costMicros:1,execute:async value=>{active++;peak=Math.max(peak,active);arrivals++;if(arrivals===2)release();await bothStarted;active--;return value+1;}});const leaf=defineWorkflow({id:'parallel-leaf',version:'1',input:z.number(),output:z.number(),nodes:[{kind:'tool',id:'childWork',tool,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'childWork',path:[]}});const tree=defineWorkflowTree({id:'parallel-tree',version:'1',input:z.number(),output:z.array(z.number()),nodes:[{kind:'tool',id:'rootWork',tool,input:{kind:'input',path:[]}},{kind:'child',id:'child',workflow:leaf,input:{kind:'input',path:[]},policy:{permissions:['tool:parallel-increment'],maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:5_000},resources:{childWork:[]}},{kind:'join',id:'joined',dependsOn:['rootWork','child']}],result:{kind:'step',stepId:'joined',path:[]}});const runtime=createWorkflowTreeRuntime({store,scope:{principalId:'parallel',projectId:'project'},permissions:{allow:['tool:parallel-increment']},policyVersion:'1',maxCostMicros:2,maxCalls:2,maxOutputBytes:1_024,workerId:'parallel-worker',maxConcurrentJobs:2});runtimes.push(runtime);const submitted=await runtime.submit(tree,{input:1,idempotencyKey:'parallel'});const finished=await runtime.runUntilSettled(tree,submitted.id);expect(finished).toMatchObject({status:'succeeded',output:[2,2]});expect(peak).toBe(2);
    }finally{await Promise.all(runtimes.map(runtime=>runtime.close()));await store.close();if(!/^mayura_tree_runtime_[a-f0-9]{32}$/.test(schema))throw new Error('Unexpected fixture schema.');const pool=new Pool({connectionString:connectionString!});try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}
  });

  it('fences competing runtime instances to one root dispatch',async()=>{
    const schema=`mayura_tree_runtime_${randomUUID().replaceAll('-','')}`;const stores=[createPostgresStore({connectionString:connectionString!,schema}),createPostgresStore({connectionString:connectionString!,schema})];const runtimes:ReturnType<typeof createWorkflowTreeRuntime>[]=[];
    try{await Promise.all(stores.map(store=>store.initialize()));let executions=0;const tool=defineTool({id:'contended-increment',version:'1',description:'Increment once.',input:z.number(),output:z.number(),effects:'none',capabilities:[],costMicros:1,execute:async value=>{executions++;await new Promise(resolve=>setTimeout(resolve,30));return value+1;}});const tree=defineWorkflowTree({id:'contended-tree',version:'1',input:z.number(),output:z.number(),nodes:[{kind:'tool',id:'work',tool,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}});const shared={scope:{principalId:'contended',projectId:'project'},permissions:{allow:['tool:contended-increment']},policyVersion:'1',maxCostMicros:1,maxCalls:1,maxOutputBytes:1_024,leaseMs:3_000} as const;const first=createWorkflowTreeRuntime({store:stores[0]!,...shared,workerId:'contender-a'});const second=createWorkflowTreeRuntime({store:stores[1]!,...shared,workerId:'contender-b'});runtimes.push(first,second);const submitted=await first.submit(tree,{input:1,idempotencyKey:'contended'});await Promise.all([first.runUntilSettled(tree,submitted.id),second.runUntilSettled(tree,submitted.id)]);const current=await first.inspect(submitted.id);const finished=current.status==='succeeded'?current:await second.runUntilSettled(tree,submitted.id);expect(finished).toMatchObject({status:'succeeded',output:2});expect(executions).toBe(1);
    }finally{await Promise.all(runtimes.map(runtime=>runtime.close()));await Promise.all(stores.map(store=>store.close()));if(!/^mayura_tree_runtime_[a-f0-9]{32}$/.test(schema))throw new Error('Unexpected fixture schema.');const pool=new Pool({connectionString:connectionString!});try{await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);}finally{await pool.end();}}
  });
});
