import { fork,type ChildProcess } from 'node:child_process';
import { mkdtemp,readFile,realpath,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename,dirname,join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach,beforeEach,describe,expect,it } from 'vitest';

interface Marker{readonly kind:'observed'|'completed'|'fixture_error';readonly runId?:string;readonly phase?:string;readonly code?:string;readonly report?:{readonly status:string;readonly outcomes:readonly {readonly kind:string;readonly rootId:string;readonly status?:string}[]};readonly repeated?:{readonly status:string;readonly outcomes:readonly unknown[]};}
const fixture=fileURLToPath(new URL('./fixtures/workflow-tree-coordinator-process.mjs',import.meta.url));const prefix='mayura-tree-coordinator-recovery-';
async function within<T>(value:Promise<T>,label:string):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([value,new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(new Error(`Timed out waiting for ${label}.`)),10_000);})]);}finally{if(timer)clearTimeout(timer);}}
class Child{readonly process:ChildProcess;readonly messages:Marker[]=[];readonly listeners=new Set<()=>void>();readonly exited:Promise<void>;failure:Error|undefined;constructor(args:string[]){this.process=fork(fixture,args,{execArgv:[],stdio:['ignore','ignore','pipe','ipc']});let stderr='';this.process.stderr?.on('data',(value:Buffer)=>{stderr=`${stderr}${value.toString()}`.slice(-4_096);});this.process.on('message',(message:Marker)=>{this.messages.push(message);if(message.kind==='fixture_error')this.failure=new Error(`Fixture failed ${message.code} at ${message.phase}. ${stderr}`);for(const listener of this.listeners)listener();});this.exited=new Promise((done,reject)=>{this.process.once('error',reject);this.process.once('exit',()=>{done();for(const listener of this.listeners)listener();});});}async marker(kind:Marker['kind']){let listener:(()=>void)|undefined;try{return await within(new Promise<Marker>((done,reject)=>{listener=()=>{const found=this.messages.find(item=>item.kind===kind);if(found)done(found);else if(this.failure)reject(this.failure);else if(this.process.exitCode!==null)reject(new Error(`Child exited before ${kind}.`));};this.listeners.add(listener);listener();}),kind);}finally{if(listener)this.listeners.delete(listener);}}async kill(){if(this.process.exitCode===null&&this.process.pid)process.kill(this.process.pid,'SIGKILL');await within(this.exited,'child exit').catch(()=>{});}}
describe('workflow-tree coordinator process recovery',()=>{let directory:string;let children:Child[];beforeEach(async()=>{directory=await mkdtemp(join(tmpdir(),prefix));children=[];});afterEach(async()=>{await Promise.all(children.map(child=>child.kill()));const actual=await realpath(directory);const root=await realpath(tmpdir());if(dirname(actual)!==root||!basename(actual).startsWith(prefix)||resolve(actual)!==resolve(directory))throw new Error('Refusing cleanup outside fixture directory.');await rm(actual,{recursive:true,force:true});});const spawn=(action:'start'|'recover',runId?:string)=>{const child=new Child([action,directory,...(runId?[runId]:[])]);children.push(child);return child;};it('resumes once after the observing coordinator is killed before continuation',async()=>{const first=spawn('start');const observed=await first.marker('observed');expect(observed.runId).toBeTypeOf('string');await first.kill();const second=spawn('recover',observed.runId);const completed=await second.marker('completed');await within(second.exited,'recovery exit');expect(completed.report).toMatchObject({status:'completed',outcomes:[{kind:'observed',rootId:observed.runId,status:'succeeded'}]});expect(completed.repeated).toMatchObject({status:'completed',outcomes:[]});const effects=(await readFile(join(directory,'effects.ndjson'),'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));expect(effects).toEqual([{runId:observed.runId,callId:`${observed.runId}/step:work`}]);},25_000);});
