// The workspace's `mayura` package: the same entry points as the published `mayura` (scripts/bundle-package.mjs), each
// re-exporting the workspace package behind it, so code in this repository (the starters) imports `mayura/...` exactly
// as users do. It is never published; releases publish the bundle.
//   node scripts/workspace-facade.mjs          write packages/mayura
//   node scripts/workspace-facade.mjs --check  fail when packages/mayura is out of date (CI)
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { workspacePackages } from './bundle-package.mjs';

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const directory = join(workspace, 'packages', 'mayura');
const root = JSON.parse(await readFile(join(workspace, 'package.json'), 'utf8'));

/** Every file the facade consists of, keyed by path relative to packages/mayura. */
async function facade() {
  const packages = await workspacePackages(); const files = new Map(); const exportsMap = {}; const dependencies = {}; const references = [];
  const module = (key, specifier) => {
    const file = key === '.' ? 'index' : key.slice(2).replaceAll('/', '__');
    files.set(`src/${file}.ts`, `// Generated by scripts/workspace-facade.mjs.\nexport * from '${specifier}';\n`);
    exportsMap[key] = { types: `./dist/${file}.d.ts`, import: `./dist/${file}.js` };
  };
  for (const { name, manifest } of packages) {
    dependencies[manifest.name] = 'workspace:*'; references.push({ path: `../${name}` });
    for (const key of Object.keys(manifest.exports ?? {})) module(key === '.' ? `./${name}` : `./${name}/${key.slice(2)}`, key === '.' ? manifest.name : `${manifest.name}/${key.slice(2)}`);
  }
  module('.', '@mayura/sdk');
  // The `mayura` command, as in the published package.
  files.set('bin.js', `#!/usr/bin/env node\n// Generated by scripts/workspace-facade.mjs: runs the workspace CLI.\nawait import(new URL('bin.js', import.meta.resolve('@mayura/cli')).href);\n`);
  files.set('package.json', `${JSON.stringify({
    name: 'mayura', version: root.version, private: true, type: 'module', sideEffects: false,
    description: 'Workspace facade with the entry points of the published mayura package. Generated by scripts/workspace-facade.mjs; never published.',
    bin: { mayura: './bin.js' },
    exports: Object.fromEntries(Object.entries(exportsMap).sort(([a], [b]) => a === '.' ? -1 : b === '.' ? 1 : a.localeCompare(b))),
    dependencies: Object.fromEntries(Object.entries(dependencies).sort()),
  }, null, 2)}\n`);
  // Node types: some entry points (terminal, server-node, storage) name Node.js stream and file types in their API.
  files.set('tsconfig.json', `${JSON.stringify({ extends: '../../tsconfig.base.json', compilerOptions: { rootDir: 'src', outDir: 'dist', types: ['node'] }, include: ['src/**/*.ts'], references }, null, 2)}\n`);
  return files;
}

const files = await facade();
if (process.argv.includes('--check')) {
  const problems = [];
  for (const [path, content] of files) if (!existsSync(join(directory, path)) || await readFile(join(directory, path), 'utf8') !== content) problems.push(path);
  const present = existsSync(join(directory, 'src')) ? (await readdir(join(directory, 'src'))).map(name => `src/${name}`) : [];
  for (const path of present) if (!files.has(path)) problems.push(`${path} (stale)`);
  assert.deepEqual(problems, [], `packages/mayura is out of date; run node scripts/workspace-facade.mjs:\n${problems.join('\n')}`);
  console.log(JSON.stringify({ status: 'current', files: files.size }));
} else {
  await rm(join(directory, 'src'), { recursive: true, force: true });
  for (const [path, content] of files) { await mkdir(dirname(join(directory, path)), { recursive: true }); await writeFile(join(directory, path), content); }
  console.log(JSON.stringify({ status: 'written', files: files.size }));
}
