import { afterEach, describe, expect, it } from 'vitest';
import { createSqliteStore } from '@mayura/storage-sqlite';
import type { JsonObject } from '@mayura/core';
import { workflowTreeState, type WorkflowTreeMethod } from '@mayura/storage-contracts';
import { workflowTreeCommand, workflowTreeResult } from '../src/workflow-tree-validation.js';

const leaf={id:'leaf',version:'1',graph:[{kind:'tool' as const,id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none' as const,capabilities:[],costMicros:1,approval:false,input:{kind:'input' as const,path:[]}}],result:{kind:'step' as const,stepId:'work',path:[]}};
const manifest={format:4 as const,id:'root',version:'1',graph:[{kind:'child' as const,id:'child',dependsOn:[],workflow:leaf,policy:{permissions:['tool:fixture/tool'],maxCostMicros:1,maxCalls:1,maxOutputBytes:128,approvalTtlMs:1_000},resources:{work:[]},input:{kind:'input' as const,path:[]}}],result:{kind:'step' as const,stepId:'child',path:[]}};
const approvalManifest={...manifest,id:'approval-root',graph:[{...manifest.graph[0]!,workflow:{...leaf,graph:[{...leaf.graph[0]!,approval:true}]}}]};
const policy={scope:{principalId:'matrix',projectId:'project'},permissions:['tool:fixture/tool'],policyVersion:'1',maxCostMicros:1,maxCalls:1,maxOutputBytes:128,approvalTtlMs:1_000};
type Case={method:WorkflowTreeMethod;command:JsonObject;response:unknown};

describe('workflow-tree response method matrix',()=>{
  const stores:ReturnType<typeof createSqliteStore>[]=[];afterEach(async()=>{await Promise.all(stores.splice(0).map(store=>store.close()));});
  it('accepts every valid method family and rejects added transport fields',async()=>{
    const store=createSqliteStore({filename:':memory:'});stores.push(store);await store.initialize();const api=store.workflowTrees;const cases:Case[]=[];
    const capture=async<T>(method:WorkflowTreeMethod,command:unknown,operation:()=>Promise<T>):Promise<T>=>{const canonical=workflowTreeCommand(method,command);const response=await operation();cases.push({method,command:canonical,response});return response;};
    cases.push({method:'initialize',command:workflowTreeCommand('initialize',{}),response:await api.initialize()});
    const submitted=await capture('submit',{manifest,policy,resources:{},input:null,idempotencyKey:'matrix'},()=>api.submit({manifest,policy,resources:{},input:null,idempotencyKey:'matrix'}));const root=submitted.snapshot;const access={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash};
    await capture('inspect',access,()=>api.inspect(access));const admitted=await capture('admitChild',{...access,parentId:root.rootId,nodeId:'child',expectedVersion:root.record.version,input:null},()=>api.admitChild({...access,parentId:root.rootId,nodeId:'child',expectedVersion:root.record.version,input:null}));const child={...access,childId:admitted.childId,childPolicyHash:admitted.policyHash};await capture('inspectChild',child,()=>api.inspectChild(child));
    const node={...child,nodeId:'work'};const prepared=await capture('prepareChildTool',{...node,expectedVersion:admitted.child.version,input:null},()=>api.prepareChildTool({...node,expectedVersion:admitted.child.version,input:null}));const claimed=await capture('claimPreparedChildTool',{...node,workerId:'worker',leaseMs:1_000},()=>api.claimPreparedChildTool({...node,workerId:'worker',leaseMs:1_000}));if(!claimed)throw new Error('fixture');const renewed=await capture('renewClaimedChildTool',{...node,claim:claimed.claim,leaseMs:2_000},()=>api.renewClaimedChildTool({...node,claim:claimed.claim,leaseMs:2_000}));await capture('startClaimedChildTool',{...node,expectedVersion:renewed.member.version,claim:renewed.claim,input:null},()=>api.startClaimedChildTool({...node,expectedVersion:renewed.member.version,claim:renewed.claim,input:null}));const receipt={callId:`${admitted.childId}/step:work`,toolId:'fixture/tool',execution:'succeeded' as const,disclosure:'withheld' as const};await capture('recordChildToolReceipt',{...node,fence:renewed.claim.fence,evidenceId:'known',receipt},()=>api.recordChildToolReceipt({...node,fence:renewed.claim.fence,evidenceId:'known',receipt}));const completed=await capture('completeChildTool',{...node,claim:renewed.claim,commandId:'complete',evidenceId:'known',outcome:'succeeded',output:1},()=>api.completeChildTool({...node,claim:renewed.claim,commandId:'complete',evidenceId:'known',outcome:'succeeded',output:1}));const finalized=await capture('finalizeChild',{...child,expectedVersion:completed.member.version,output:1},()=>api.finalizeChild({...child,expectedVersion:completed.member.version,output:1}));const joined=await capture('joinChild',{...access,nodeId:'child',expectedVersion:finalized.root.record.version},()=>api.joinChild({...access,nodeId:'child',expectedVersion:finalized.root.record.version}));await capture('finalizeRoot',{...access,expectedVersion:joined.record.version,output:1},()=>api.finalizeRoot({...access,expectedVersion:joined.record.version,output:1}));
    const approvalRoot=(await api.submit({manifest:approvalManifest,policy,resources:{},input:null,idempotencyKey:'approval'})).snapshot;const approvalAccess={scope:approvalRoot.record.scope,rootId:approvalRoot.rootId,rootPolicyHash:approvalRoot.policyHash};const approvalChild=await api.admitChild({...approvalAccess,parentId:approvalRoot.rootId,nodeId:'child',expectedVersion:1,input:null});const approvalNode={...approvalAccess,childId:approvalChild.childId,childPolicyHash:approvalChild.policyHash,nodeId:'work'};const requested=await capture('requestChildApproval',{...approvalNode,expectedVersion:approvalChild.child.version,input:null},()=>api.requestChildApproval({...approvalNode,expectedVersion:approvalChild.child.version,input:null}));const approval=workflowTreeState(requested.member).steps['work']!.approval as {digest:string};await capture('approveChildTool',{...approvalNode,expectedVersion:requested.member.version,digest:approval.digest,humanId:'reviewer'},()=>api.approveChildTool({...approvalNode,expectedVersion:requested.member.version,digest:approval.digest,humanId:'reviewer'}));
    const childCancelSubmission=(await api.submit({manifest,policy,resources:{},input:null,idempotencyKey:'child-cancel'})).snapshot;const childCancelAccess={scope:childCancelSubmission.record.scope,rootId:childCancelSubmission.rootId,rootPolicyHash:childCancelSubmission.policyHash};const childCancelMember=await api.admitChild({...childCancelAccess,parentId:childCancelSubmission.rootId,nodeId:'child',expectedVersion:1,input:null});const cancelChild={...childCancelAccess,childId:childCancelMember.childId,childPolicyHash:childCancelMember.policyHash};await api.prepareChildTool({...cancelChild,nodeId:'work',expectedVersion:childCancelMember.child.version,input:null});await capture('cancelChild',{...cancelChild,expectedVersion:2,commandId:'child-cancel'},()=>api.cancelChild({...cancelChild,expectedVersion:2,commandId:'child-cancel'}));
    const rootCancelSubmission=(await api.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root-cancel'})).snapshot;const cancelAccess={scope:rootCancelSubmission.record.scope,rootId:rootCancelSubmission.rootId,rootPolicyHash:rootCancelSubmission.policyHash};const rootCancelMember=await api.admitChild({...cancelAccess,parentId:rootCancelSubmission.rootId,nodeId:'child',expectedVersion:1,input:null});await api.prepareChildTool({...cancelAccess,childId:rootCancelMember.childId,childPolicyHash:rootCancelMember.policyHash,nodeId:'work',expectedVersion:rootCancelMember.child.version,input:null});const current=(await api.inspect(cancelAccess))!;await capture('cancelRoot',{...cancelAccess,expectedVersion:current.record.version,commandId:'root-cancel'},()=>api.cancelRoot({...cancelAccess,expectedVersion:current.record.version,commandId:'root-cancel'}));
    const recovery=(await api.submit({manifest,policy,resources:{},input:null,idempotencyKey:'recovery'})).snapshot;const recoveryAccess={scope:recovery.record.scope,rootId:recovery.rootId,rootPolicyHash:recovery.policyHash};await capture('recoverExpired',{...recoveryAccess,limit:128},()=>api.recoverExpired({...recoveryAccess,limit:128}));
    expect(cases.map(item=>item.method)).toHaveLength(19);for(const item of cases){expect(()=>workflowTreeResult(item.method,item.response,item.command)).not.toThrow();if(item.method==='initialize'){expect(()=>workflowTreeResult(item.method,{},item.command)).toThrowError(expect.objectContaining({code:'STORAGE_UNAVAILABLE'}));continue;}if(item.response===undefined)continue;const hostile={...(structuredClone(item.response) as JsonObject),unexpected:true};expect(()=>workflowTreeResult(item.method,hostile,item.command)).toThrowError(expect.objectContaining({code:'STORAGE_UNAVAILABLE'}));const identity=structuredClone(item.response) as JsonObject;const rootView=item.method==='submit'?(identity['snapshot'] as JsonObject):['inspect','joinChild','finalizeRoot'].includes(item.method)?identity:identity['root'] as JsonObject;if(rootView){rootView['rootId']='f'.repeat(64);expect(()=>workflowTreeResult(item.method,identity,item.command)).toThrowError(expect.objectContaining({code:'STORAGE_UNAVAILABLE'}));}}
    const rootCancellation=cases.find(item=>item.method==='cancelRoot')!;const missingMember=structuredClone(rootCancellation.response) as JsonObject;missingMember['members']=[];expect((missingMember['jobs'] as unknown[]).length).toBe(1);expect(()=>workflowTreeResult('cancelRoot',missingMember,rootCancellation.command)).toThrowError(expect.objectContaining({code:'STORAGE_UNAVAILABLE'}));
    expect(prepared.created).toBe(true);
  });
});
