import Database from 'better-sqlite3';
import { describe, expect, it } from 'vitest';
import {
  DurableBudgetDatabase, ScheduledWorkflowDatabase, SchedulerDatabase, WorkflowTreeDatabase,
  type SchedulerBackend, type SchedulerSession,
} from '@mayura/storage-sql/host';
import type { WorkflowTreeManifest, WorkflowTreePolicyManifest } from '@mayura/storage-contracts';
import { workflowTreeState } from '@mayura/storage-contracts';

function backend(database:Database.Database):SchedulerBackend{
  const session:SchedulerSession={query:async<T>(sql:string,parameters:readonly unknown[]=[])=>{const statement=database.prepare(sql);if(statement.reader)return statement.all(...parameters) as T[];statement.run(...parameters);return[];}};
  return{dialect:'sqlite',prefix:'',transaction:async body=>{database.exec('BEGIN IMMEDIATE');try{const value=await body(session);database.exec('COMMIT');return value;}catch(error){database.exec('ROLLBACK');throw error;}}};
}
function base(database:Database.Database):void{database.pragma('foreign_keys = ON');database.exec(`
  CREATE TABLE mayura_aggregates (scope TEXT NOT NULL,id TEXT NOT NULL,idempotency_key TEXT NOT NULL,definition_hash TEXT NOT NULL,submission_digest TEXT NOT NULL,version INTEGER NOT NULL,event_sequence INTEGER NOT NULL,state TEXT NOT NULL,PRIMARY KEY(scope,id),UNIQUE(scope,idempotency_key));
  CREATE TABLE mayura_events (scope TEXT NOT NULL,aggregate_id TEXT NOT NULL,sequence INTEGER NOT NULL,type TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(scope,aggregate_id,sequence),FOREIGN KEY(scope,aggregate_id) REFERENCES mayura_aggregates(scope,id));
  CREATE TABLE mayura_workflow_owners (scope TEXT NOT NULL,aggregate_id TEXT NOT NULL,profile INTEGER NOT NULL,aggregate_version INTEGER NOT NULL,definition_hash TEXT NOT NULL,policy_hash TEXT NOT NULL,resource_hash TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(scope,aggregate_id),FOREIGN KEY(scope,aggregate_id) REFERENCES mayura_aggregates(scope,id));`);}
const leaf={id:'leaf',version:'1',graph:[{kind:'tool' as const,id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none' as const,capabilities:[],costMicros:2,approval:false,input:{kind:'input' as const,path:[]}}],result:{kind:'step' as const,stepId:'work',path:[]}};
const manifest:WorkflowTreeManifest={format:4,id:'root',version:'1',graph:[{kind:'child',id:'child',dependsOn:[],workflow:leaf,policy:{permissions:['tool:fixture/tool'],maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000},resources:{work:[]},input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'child',path:[]}};
const approvalLeaf={...leaf,graph:[{...leaf.graph[0]!,approval:true}]};
const approvalManifest:WorkflowTreeManifest={format:4,id:'approval-root',version:'1',graph:[{kind:'child',id:'child',dependsOn:[],workflow:approvalLeaf,policy:{permissions:['tool:fixture/tool'],maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:500},resources:{work:[]},input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'child',path:[]}};
const rootToolManifest:WorkflowTreeManifest={format:4,id:'root-tool',version:'1',graph:[{kind:'tool',id:'work',dependsOn:[],tool:'fixture/tool',toolVersion:'1',effects:'none',capabilities:[],costMicros:2,approval:true,input:{kind:'input',path:[]}}],result:{kind:'step',stepId:'work',path:[]}};
const policy:WorkflowTreePolicyManifest={scope:{principalId:'owner',projectId:'project'},permissions:['tool:fixture/tool'],policyVersion:'1',maxCostMicros:2,maxCalls:1,maxOutputBytes:1_024,approvalTtlMs:1_000};

describe('workflow-tree atomic root enrollment',()=>{
  it('commits one profile-3 root, membership and scheduler-owned ledger and retries exactly',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const scheduler=new SchedulerDatabase(selected);const trees=new WorkflowTreeDatabase(selected,scheduler);
    await trees.initialize();const first=await trees.submit({manifest,policy,resources:{},input:{value:1},idempotencyKey:'one'});const second=await trees.submit({manifest,policy,resources:{},input:{value:1},idempotencyKey:'one'});
    expect(first.created).toBe(true);expect(second.created).toBe(false);expect(second.snapshot).toEqual(first.snapshot);expect(first.snapshot).toMatchObject({profile:'scheduled-v3',accountId:'root',budget:{owner:'workflow-tree-v1',accounts:[{id:'root',maxCostMicros:2,maxCalls:1}]}});
    expect(database.prepare('SELECT profile FROM mayura_workflow_owners').pluck().all()).toEqual([3]);expect(database.prepare('SELECT account_id FROM mayura_workflow_tree_members').pluck().all()).toEqual(['root']);
    const legacy=new ScheduledWorkflowDatabase(selected,scheduler);await legacy.execute('initialize',{});await expect(legacy.execute('inspect',{scope:first.snapshot.record.scope,id:first.snapshot.rootId,policyHash:first.snapshot.policyHash})).rejects.toMatchObject({code:'CONFLICT'});
    const host=new DurableBudgetDatabase(selected);await host.execute('initialize',{});await expect(host.execute('inspect',{scope:first.snapshot.record.scope,id:first.snapshot.rootId,policyHash:first.snapshot.policyHash})).resolves.toBeUndefined();database.close();
  });

  it('executes one approval-enabled root-local tool through atomic format-4 transitions',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const submitted=(await trees.submit({manifest:rootToolManifest,policy,resources:{work:[]},input:1,idempotencyKey:'root-tool'})).snapshot;const access={scope:submitted.record.scope,rootId:submitted.rootId,rootPolicyHash:submitted.policyHash,nodeId:'work'};const requested=await trees.requestRootApproval({...access,expectedVersion:submitted.record.version,input:1});const review=workflowTreeState(requested.record).steps['work']!.approval as {digest:string};const approved=await trees.approveRootTool({...access,expectedVersion:requested.record.version,digest:review.digest,humanId:'reviewer'});const prepared=await trees.prepareRootTool({...access,expectedVersion:approved.record.version,input:1});expect(prepared).toMatchObject({created:true,job:{runId:submitted.rootId,nodeId:'work',state:'ready'},root:{budget:{accounts:[expect.objectContaining({id:'root',reservedMicros:2,heldCalls:1})]}}});const claimed=await trees.claimPreparedRootTool({...access,workerId:'root-worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');const started=await trees.startClaimedRootTool({...access,expectedVersion:claimed.root.record.version,claim:claimed.claim,input:1});expect(started.status).toBe('started');const renewed=await trees.renewClaimedRootTool({...access,claim:claimed.claim,leaseMs:2_000});const receipt={callId:`${submitted.rootId}/step:work`,toolId:'fixture/tool',execution:'succeeded' as const,disclosure:'withheld' as const};const recorded=await trees.recordRootToolReceipt({...access,fence:renewed.claim.fence,evidenceId:'root-known',receipt});expect(recorded.root.budget.accounts[0]).toMatchObject({spentMicros:2,reservedMicros:0,calls:1});const completed=await trees.completeRootTool({...access,claim:renewed.claim,commandId:'root-complete',evidenceId:'root-known',outcome:'succeeded',output:2});expect(workflowTreeState(completed.root.record)).toMatchObject({status:'running',steps:{work:{status:'succeeded',output:2}}});const finished=await trees.finalizeRoot({scope:access.scope,rootId:access.rootId,rootPolicyHash:access.rootPolicyHash,expectedVersion:completed.root.record.version,output:2});expect(workflowTreeState(finished.record)).toMatchObject({status:'succeeded',output:2});expect(finished.budget.accounts[0]).toMatchObject({id:'root',closed:true,spentMicros:2});database.close();
  });

  it('rolls back ledger and aggregate when the final membership write fails',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();
    database.exec("CREATE TRIGGER reject_tree_member BEFORE INSERT ON mayura_workflow_tree_members BEGIN SELECT RAISE(ABORT, 'rejected'); END;");
    await expect(trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'rollback'})).rejects.toBeDefined();
    expect(database.prepare('SELECT COUNT(*) FROM mayura_aggregates').pluck().get()).toBe(0);expect(database.prepare('SELECT COUNT(*) FROM mayura_workflow_tree_budgets').pluck().get()).toBe(0);expect(database.prepare('SELECT COUNT(*) FROM mayura_workflow_tree_budget_events').pluck().get()).toBe(0);database.close();
  });

  it('rejects widened child authority and an impossible required plan before persistence',async()=>{
    const database=new Database(':memory:');base(database);const trees=new WorkflowTreeDatabase(backend(database),new SchedulerDatabase(backend(database)));await trees.initialize();
    const original=manifest.graph[0]!;if(original.kind!=='child')throw new Error('fixture');
    const widened={...manifest,graph:[{...original,policy:{...original.policy,permissions:['host:admin']}}]} as WorkflowTreeManifest;
    await expect(trees.submit({manifest:widened,policy,resources:{},input:null,idempotencyKey:'wide'})).rejects.toBeDefined();
    await expect(trees.submit({manifest,policy:{...policy,maxCostMicros:1},resources:{},input:null,idempotencyKey:'small'})).rejects.toBeDefined();
    expect(database.prepare('SELECT COUNT(*) FROM mayura_aggregates').pluck().get()).toBe(0);database.close();
  });

  it('admits exactly one derived child and account with semantic retry',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();
    const submitted=await trees.submit({manifest,policy,resources:{},input:{value:1},idempotencyKey:'root'});const root=submitted.snapshot;
    const admitted=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:root.record.version,input:{value:1}});
    expect(admitted.created).toBe(true);expect(admitted.root).toMatchObject({record:{version:2},budget:{version:2}});expect(admitted.root.budget.accounts).toEqual(expect.arrayContaining([expect.objectContaining({id:'root'}),expect.objectContaining({id:admitted.accountId,parentId:'root'})]));
    expect(workflowTreeState(admitted.child)).toMatchObject({format:4,rootId:root.rootId,accountId:admitted.accountId,budgetVersion:2});
    const retry=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:root.record.version,input:{value:1}});expect(retry.created).toBe(false);expect(retry.childId).toBe(admitted.childId);
    await expect(trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:2,input:{value:2}})).rejects.toMatchObject({code:'CONFLICT'});
    expect(database.prepare('SELECT COUNT(*) FROM mayura_workflow_owners').pluck().get()).toBe(2);expect(database.prepare('SELECT COUNT(*) FROM mayura_workflow_tree_members').pluck().get()).toBe(2);database.close();
  });

  it('rolls child account, aggregate and parent transition back together',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();
    const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'})).snapshot;
    database.exec("CREATE TRIGGER reject_child_member BEFORE INSERT ON mayura_workflow_tree_members WHEN NEW.account_id <> 'root' BEGIN SELECT RAISE(ABORT, 'rejected'); END;");
    await expect(trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null})).rejects.toBeDefined();
    const reopened=await trees.inspect(root.record.scope,root.rootId,root.policyHash);expect(reopened).toMatchObject({record:{version:1},budget:{version:1,accounts:[{id:'root'}]}});expect(database.prepare('SELECT COUNT(*) FROM mayura_aggregates').pluck().get()).toBe(1);database.close();
  });

  it('atomically prepares one child tool with its shared-ledger ticket and scheduler job',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const scheduler=new SchedulerDatabase(selected);const trees=new WorkflowTreeDatabase(selected,scheduler);await trees.initialize();
    const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await expect(trees.finalizeRoot({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:2,output:null})).rejects.toMatchObject({code:'CONFLICT'});
    const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null};
    const prepared=await trees.prepareChildTool(command);expect(prepared.created).toBe(true);expect(prepared.job).toMatchObject({state:'ready',runId:child.childId,nodeId:'work'});expect(prepared.root).toMatchObject({record:{version:3},budget:{version:3}});expect(prepared.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({reservedMicros:2,heldCalls:1});expect(workflowTreeState(prepared.member)).toMatchObject({budgetVersion:3,reservedMicros:2,steps:{work:{candidateHash:expect.stringMatching(/^[a-f0-9]{64}$/),costReserved:2}}});
    const retry=await trees.prepareChildTool(command);expect(retry.created).toBe(false);expect(retry.job.jobId).toBe(prepared.job.jobId);await expect(trees.prepareChildTool({...command,input:{changed:true},expectedVersion:2})).rejects.toMatchObject({code:'CONFLICT'});
    const claimed=await trees.claimPreparedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',workerId:'worker-a',leaseMs:1_000});expect(claimed).toMatchObject({job:{state:'leased',workerId:'worker-a',fence:1},claim:{workerId:'worker-a',fence:1},member:{version:3}});await expect(trees.claimPreparedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',workerId:'worker-b',leaseMs:1_000})).resolves.toBeUndefined();
    if(!claimed)throw new Error('fixture');const started=await trees.startClaimedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:claimed.member.version,claim:claimed.claim,input:null});expect(started).toMatchObject({status:'started',job:{state:'started'},member:{version:4},root:{record:{version:4},budget:{version:4}}});expect(started.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({calls:1,heldCalls:0,reservedMicros:2});expect(workflowTreeState(started.member)).toMatchObject({budgetVersion:4,steps:{work:{status:'dispatching',costReserved:2}}});
    const retriedStart=await trees.startClaimedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:claimed.member.version,claim:claimed.claim,input:null});expect(retriedStart.status).toBe('already_started');await expect(trees.startClaimedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:4,claim:claimed.claim,input:{changed:true}})).rejects.toMatchObject({code:'CONFLICT'});
    const receipt={callId:`${child.childId}/step:work`,toolId:'fixture/tool',execution:'succeeded' as const,disclosure:'withheld' as const};const recorded=await trees.recordChildToolReceipt({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'evidence-1',receipt});expect(recorded).toMatchObject({disposition:'current',root:{record:{version:5},budget:{version:5}},member:{version:5}});expect(recorded.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({spentMicros:2,reservedMicros:0,calls:1});expect(workflowTreeState(recorded.member)).toMatchObject({spentMicros:2,reservedMicros:0,steps:{work:{status:'dispatching',costReserved:0,receipt}}});
    const receiptRetry=await trees.recordChildToolReceipt({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'evidence-1',receipt});expect(receiptRetry.root.record.version).toBe(5);expect(receiptRetry.member.version).toBe(5);
    const completion={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',claim:claimed.claim,commandId:'complete-1',evidenceId:'evidence-1',outcome:'succeeded' as const,output:{answer:42}};const completed=await trees.completeChildTool(completion);expect(completed).toMatchObject({root:{record:{version:5}},member:{version:6},job:{state:'succeeded',receipt:{execution:'succeeded',disclosure:'released'},output:{answer:42}}});expect(workflowTreeState(completed.member)).toMatchObject({status:'running',steps:{work:{status:'succeeded',output:{answer:42},receipt:{execution:'succeeded',disclosure:'released'}}}});const completedRetry=await trees.completeChildTool(completion);expect(completedRetry.member.version).toBe(6);
    const finalized=await trees.finalizeChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,expectedVersion:completed.member.version,output:{answer:42}});expect(finalized).toMatchObject({root:{record:{version:6},budget:{version:6}},member:{version:7}});expect(finalized.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({closed:true,spentMicros:2,reservedMicros:0});expect(workflowTreeState(finalized.member)).toMatchObject({status:'succeeded',budgetVersion:6,output:{answer:42}});const finalizedRetry=await trees.finalizeChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,expectedVersion:completed.member.version,output:{answer:42}});expect(finalizedRetry.member.version).toBe(7);
    const joined=await trees.joinChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'child',expectedVersion:finalized.root.record.version});expect(joined.record.version).toBe(7);expect(workflowTreeState(joined.record)).toMatchObject({status:'running',budgetVersion:6,steps:{child:{status:'succeeded',output:{answer:42},child:{runId:child.childId,joinedVersion:7}}}});const joinedRetry=await trees.joinChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'child',expectedVersion:finalized.root.record.version});expect(joinedRetry.record.version).toBe(7);
    const rootCompletion={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:joined.record.version,output:{answer:42}};const finished=await trees.finalizeRoot(rootCompletion);expect(finished).toMatchObject({record:{version:8},budget:{version:7,accounts:expect.arrayContaining([expect.objectContaining({id:'root',closed:true}),expect.objectContaining({id:child.accountId,closed:true})])}});expect(workflowTreeState(finished.record)).toMatchObject({status:'succeeded',budgetVersion:7,output:{answer:42}});const finishedRetry=await trees.finalizeRoot(rootCompletion);expect(finishedRetry.record.version).toBe(8);
    await expect(scheduler.execute('claim',{scope:root.record.scope,workerId:'legacy',limit:1,leaseMs:1_000})).resolves.toEqual([]);database.close();
  });

  it('binds child approval to the exact candidate and rejects stale review evidence',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest:approvalManifest,policy,resources:{},input:null,idempotencyKey:'approval'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work'};const requested=await trees.requestChildApproval({...command,expectedVersion:child.child.version,input:{value:1}});const first=workflowTreeState(requested.member).steps['work']!.approval as {digest:string};expect(workflowTreeState(requested.member)).toMatchObject({status:'waiting',steps:{work:{status:'waiting',approval:{digest:expect.stringMatching(/^[a-f0-9]{64}$/),humanId:null}}}});const retried=await trees.requestChildApproval({...command,expectedVersion:child.child.version,input:{value:1}});expect(retried.member.version).toBe(requested.member.version);await expect(trees.requestChildApproval({...command,expectedVersion:requested.member.version,input:{value:2}})).rejects.toMatchObject({code:'CONFLICT'});await expect(trees.approveChildTool({...command,expectedVersion:requested.member.version,digest:'0'.repeat(64),humanId:'reviewer'})).rejects.toMatchObject({code:'CONFLICT'});await new Promise(resolve=>setTimeout(resolve,600));await expect(trees.approveChildTool({...command,expectedVersion:requested.member.version,digest:first.digest,humanId:'reviewer'})).rejects.toMatchObject({code:'CONFLICT'});const renewed=await trees.requestChildApproval({...command,expectedVersion:requested.member.version,input:{value:1}});const second=workflowTreeState(renewed.member).steps['work']!.approval as {digest:string};expect(second.digest).not.toBe(first.digest);const approved=await trees.approveChildTool({...command,expectedVersion:renewed.member.version,digest:second.digest,humanId:'reviewer'});expect(workflowTreeState(approved.member)).toMatchObject({status:'running',steps:{work:{status:'approved',approval:{digest:second.digest,humanId:'reviewer'}}}});const approvalRetry=await trees.approveChildTool({...command,expectedVersion:renewed.member.version,digest:second.digest,humanId:'reviewer'});expect(approvalRetry.member.version).toBe(approved.member.version);const prepared=await trees.prepareChildTool({...command,expectedVersion:approved.member.version,input:{value:1}});expect(prepared.created).toBe(true);database.close();
  });

  it('cancels approved prepared work that expires before first dispatch',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest:approvalManifest,policy,resources:{},input:null,idempotencyKey:'prepared-expiry'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work'};const requested=await trees.requestChildApproval({...command,expectedVersion:child.child.version,input:null});const review=workflowTreeState(requested.member).steps['work']!.approval as {digest:string};const approved=await trees.approveChildTool({...command,expectedVersion:requested.member.version,digest:review.digest,humanId:'reviewer'});await trees.prepareChildTool({...command,expectedVersion:approved.member.version,input:null});const claimed=await trees.claimPreparedChildTool({...command,workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await new Promise(resolve=>setTimeout(resolve,600));await expect(trees.startClaimedChildTool({...command,expectedVersion:claimed.member.version,claim:claimed.claim,input:null})).rejects.toMatchObject({code:'STALE_CLAIM'});const recovered=await trees.recoverExpired({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,limit:1});expect(recovered.jobs).toEqual([expect.objectContaining({state:'cancelled',startedAtMs:null})]);expect(recovered.root.budget.reservations).toEqual([expect.objectContaining({status:'cancelled'})]);expect(recovered.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({spentMicros:0,reservedMicros:0,calls:0,heldCalls:0});expect(workflowTreeState(recovered.members[0]!)).toMatchObject({status:'blocked',reservedMicros:0,steps:{work:{status:'blocked',costReserved:0}}});database.close();
  });

  it('recovers an expired approval-prepared root tool without treating the root as a child',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest:rootToolManifest,policy:{...policy,approvalTtlMs:500},resources:{work:[]},input:null,idempotencyKey:'root-prepared-expiry'})).snapshot;const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'work'};const requested=await trees.requestRootApproval({...command,expectedVersion:root.record.version,input:null});const review=workflowTreeState(requested.record).steps['work']!.approval as {digest:string};const approved=await trees.approveRootTool({...command,expectedVersion:requested.record.version,digest:review.digest,humanId:'reviewer'});await trees.prepareRootTool({...command,expectedVersion:approved.record.version,input:null});const claimed=await trees.claimPreparedRootTool({...command,workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await new Promise(resolve=>setTimeout(resolve,600));const recovered=await trees.recoverExpired({scope:command.scope,rootId:command.rootId,rootPolicyHash:command.rootPolicyHash,limit:1});expect(recovered.members).toEqual([]);expect(recovered.jobs).toEqual([expect.objectContaining({state:'cancelled',startedAtMs:null})]);expect(recovered.root.budget.accounts[0]).toMatchObject({id:'root',spentMicros:0,reservedMicros:0,calls:0,heldCalls:0});expect(workflowTreeState(recovered.root.record)).toMatchObject({status:'blocked',reservedMicros:0,steps:{work:{status:'blocked',costReserved:0}}});database.close();
  });

  it('quarantines an expired started root tool under its root account',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest:rootToolManifest,policy:{...policy,approvalTtlMs:5_000},resources:{work:[]},input:null,idempotencyKey:'root-started-expiry'})).snapshot;const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'work'};const requested=await trees.requestRootApproval({...command,expectedVersion:root.record.version,input:null});const review=workflowTreeState(requested.record).steps['work']!.approval as {digest:string};const approved=await trees.approveRootTool({...command,expectedVersion:requested.record.version,digest:review.digest,humanId:'reviewer'});await trees.prepareRootTool({...command,expectedVersion:approved.record.version,input:null});const claimed=await trees.claimPreparedRootTool({...command,workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await trees.startClaimedRootTool({...command,expectedVersion:claimed.root.record.version,claim:claimed.claim,input:null});await new Promise(resolve=>setTimeout(resolve,1_100));const recovered=await trees.recoverExpired({scope:command.scope,rootId:command.rootId,rootPolicyHash:command.rootPolicyHash,limit:1});expect(recovered.members).toEqual([]);expect(recovered.jobs).toEqual([expect.objectContaining({state:'outcome_unknown'})]);expect(recovered.root.budget.accounts[0]).toMatchObject({id:'root',reservedMicros:2,calls:1,closed:false});expect(workflowTreeState(recovered.root.record)).toMatchObject({status:'outcome_unknown',reservedMicros:2,steps:{work:{status:'unknown',costReserved:2}}});database.close();
  },10_000);

  it('rolls a financial hold and scheduler reservation back when job linkage fails',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'root'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});
    database.exec("CREATE TRIGGER reject_tree_job BEFORE INSERT ON mayura_workflow_tree_jobs BEGIN SELECT RAISE(ABORT, 'rejected'); END;");await expect(trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null})).rejects.toBeDefined();
    const current=await trees.inspect(root.record.scope,root.rootId,root.policyHash);expect(current).toMatchObject({record:{version:2},budget:{version:2,reservations:[]}});expect(database.prepare('SELECT COUNT(*) FROM mayura_scheduler_jobs').pluck().get()).toBe(0);database.close();
  });

  it('retains unknown child cost and settles later known evidence exactly once',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'unknown'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null});const claimed=await trees.claimPreparedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await trees.startClaimedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:claimed.member.version,claim:claimed.claim,input:null});
    const baseReceipt={callId:`${child.childId}/step:work`,toolId:'fixture/tool',disclosure:'withheld' as const};const unknown=await trees.recordChildToolReceipt({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'unknown',receipt:{...baseReceipt,execution:'unknown' as const}});expect(unknown.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({spentMicros:0,reservedMicros:2,calls:1});expect(workflowTreeState(unknown.member)).toMatchObject({status:'outcome_unknown',spentMicros:0,reservedMicros:2,steps:{work:{status:'unknown',costReserved:2,receipt:{execution:'unknown'}}}});
    const known=await trees.recordChildToolReceipt({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'known',receipt:{...baseReceipt,execution:'failed' as const}});expect(known.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({closed:true,spentMicros:2,reservedMicros:0,calls:1});expect(workflowTreeState(known.member)).toMatchObject({status:'outcome_unknown',spentMicros:2,reservedMicros:0,steps:{work:{status:'unknown',costReserved:0,receipt:{execution:'failed'}}}});const joined=await trees.joinChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,nodeId:'child',expectedVersion:known.root.record.version});expect(workflowTreeState(joined.record)).toMatchObject({status:'outcome_unknown',steps:{child:{status:'unknown',output:null,child:{joinedVersion:known.member.version}}}});database.close();
  });

  it('atomically cancels held child work and closes the shared root authority',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const scheduler=new SchedulerDatabase(selected);const trees=new WorkflowTreeDatabase(selected,scheduler);await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'held-cancel'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null});
    const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:3,commandId:'cancel-held'};const cancelled=await trees.cancelRoot(command);expect(cancelled.root).toMatchObject({record:{version:4},budget:{version:5,reservations:[expect.objectContaining({status:'cancelled'})]}});expect(cancelled.root.budget.accounts.find(account=>account.id==='root')).toMatchObject({closed:true,reservedMicros:0});expect(cancelled.jobs).toEqual([expect.objectContaining({state:'cancelled'})]);expect(workflowTreeState(cancelled.root.record)).toMatchObject({status:'cancelled',budgetVersion:5,steps:{child:{status:'skipped'}}});expect(cancelled.members).toHaveLength(1);expect(workflowTreeState(cancelled.members[0]!)).toMatchObject({status:'cancelled',reservedMicros:0,budgetVersion:5,steps:{work:{status:'skipped',costReserved:0}}});const retry=await trees.cancelRoot(command);expect(retry).toMatchObject({root:{record:{version:4}},members:[],jobs:[]});const preparedRetry=await trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:3,input:null});expect(preparedRetry).toMatchObject({created:false,job:{state:'cancelled'},root:{record:{version:4}}});await expect(scheduler.execute('claim',{scope:root.record.scope,workerId:'legacy',limit:1,leaseMs:1_000})).resolves.toEqual([]);database.close();
  });

  it('cancels one child account without initially closing its root or siblings',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'child-cancel'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null});const command={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,expectedVersion:2,commandId:'cancel-child'};const cancelled=await trees.cancelChild(command);expect(cancelled).toMatchObject({root:{record:{version:4},budget:{version:5}},member:{version:3},jobs:[{state:'cancelled'}]});expect(cancelled.root.budget.accounts.find(account=>account.id==='root')).toMatchObject({closed:false});expect(cancelled.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({closed:true,reservedMicros:0});expect(workflowTreeState(cancelled.root.record)).toMatchObject({status:'waiting',steps:{child:{status:'waiting'}}});expect(workflowTreeState(cancelled.member)).toMatchObject({status:'cancelled',steps:{work:{status:'skipped'}}});const retry=await trees.cancelChild(command);expect(retry).toMatchObject({root:{record:{version:4}},member:{version:3},jobs:[]});await expect(trees.finalizeRoot({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:4,output:null})).rejects.toMatchObject({code:'CONFLICT'});const propagated=await trees.cancelRoot({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:4,commandId:'propagate-child-cancel'});expect(propagated).toMatchObject({root:{record:{version:5},budget:{version:6}},members:[],jobs:[]});expect(workflowTreeState(propagated.root.record)).toMatchObject({status:'cancelled',steps:{child:{status:'skipped'}}});database.close();
  });

  it('quarantines started child work on cancellation and admits late cost without result resurrection',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'started-cancel'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});await trees.prepareChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:1,input:null});const claimed=await trees.claimPreparedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',workerId:'worker',leaseMs:1_000});if(!claimed)throw new Error('fixture');await trees.startClaimedChildTool({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',expectedVersion:claimed.member.version,claim:claimed.claim,input:null});
    const cancelled=await trees.cancelRoot({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,expectedVersion:4,commandId:'cancel-started'});expect(cancelled.root).toMatchObject({record:{version:5},budget:{version:6,reservations:[expect.objectContaining({status:'unknown'})]}});expect(cancelled.jobs).toEqual([expect.objectContaining({state:'outcome_unknown'})]);expect(workflowTreeState(cancelled.root.record)).toMatchObject({status:'cancelled',steps:{child:{status:'unknown'}}});expect(workflowTreeState(cancelled.members[0]!)).toMatchObject({status:'outcome_unknown',reservedMicros:2,steps:{work:{status:'unknown',costReserved:2}}});
    const late=await trees.recordChildToolReceipt({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work',fence:claimed.claim.fence,evidenceId:'late-known',receipt:{callId:`${child.childId}/step:work`,toolId:'fixture/tool',execution:'failed',disclosure:'withheld'}});expect(late).toMatchObject({disposition:'late',root:{record:{version:6},budget:{version:8,reservations:[expect.objectContaining({status:'settled',actualMicros:2})]}}});expect(late.root.budget.accounts.find(account=>account.id===child.accountId)).toMatchObject({closed:true,reservedMicros:0,spentMicros:2});expect(workflowTreeState(late.root.record)).toMatchObject({status:'cancelled',output:null});expect(workflowTreeState(late.member)).toMatchObject({status:'outcome_unknown',reservedMicros:0,spentMicros:2,output:null,steps:{work:{status:'unknown',costReserved:0}}});database.close();
  });

  it('releases an expired lease but quarantines an expired started attempt',async()=>{
    const database=new Database(':memory:');base(database);const selected=backend(database);const trees=new WorkflowTreeDatabase(selected,new SchedulerDatabase(selected));await trees.initialize();const root=(await trees.submit({manifest,policy,resources:{},input:null,idempotencyKey:'recover'})).snapshot;const child=await trees.admitChild({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,parentId:root.rootId,nodeId:'child',expectedVersion:1,input:null});const prepared={scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,childId:child.childId,childPolicyHash:child.policyHash,nodeId:'work'};await trees.prepareChildTool({...prepared,expectedVersion:1,input:null});const first=await trees.claimPreparedChildTool({...prepared,workerId:'worker-a',leaseMs:1_000});if(!first)throw new Error('fixture');await new Promise(resolve=>setTimeout(resolve,1_100));const released=await trees.recoverExpired({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,limit:1});expect(released).toMatchObject({root:{record:{version:3},budget:{version:3}},members:[{version:4}],jobs:[{state:'ready',fence:1}]});expect(workflowTreeState(released.members[0]!)).toMatchObject({status:'running',reservedMicros:2,steps:{work:{status:'pending',costReserved:2}}});const second=await trees.claimPreparedChildTool({...prepared,workerId:'worker-b',leaseMs:1_000});if(!second)throw new Error('fixture');expect(second.claim.fence).toBe(2);await trees.startClaimedChildTool({...prepared,expectedVersion:second.member.version,claim:second.claim,input:null});await new Promise(resolve=>setTimeout(resolve,1_100));const unknown=await trees.recoverExpired({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,limit:1});expect(unknown).toMatchObject({root:{record:{version:5},budget:{version:5,reservations:[expect.objectContaining({status:'unknown'})]}},members:[{version:7}],jobs:[{state:'outcome_unknown',fence:2}]});expect(workflowTreeState(unknown.members[0]!)).toMatchObject({status:'outcome_unknown',reservedMicros:2,budgetVersion:5,steps:{work:{status:'unknown',costReserved:2}}});const retry=await trees.recoverExpired({scope:root.record.scope,rootId:root.rootId,rootPolicyHash:root.policyHash,limit:1});expect(retry).toMatchObject({root:{record:{version:5}},members:[],jobs:[]});database.close();
  },10_000);
});
